// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metaMessage.proto

package tud.seemuh.nfcgate.network.meta;

public final class MetaMessage {
  private MetaMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tud.seemuh.nfcgate.network.meta.Wrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData NFCData = 2;</code>
     */
    boolean hasNFCData();
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData NFCData = 2;</code>
     */
    tud.seemuh.nfcgate.network.c2c.C2C.NFCData getNFCData();
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData NFCData = 2;</code>
     */
    tud.seemuh.nfcgate.network.c2c.C2C.NFCDataOrBuilder getNFCDataOrBuilder();

    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.Anticol Anticol = 3;</code>
     */
    boolean hasAnticol();
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.Anticol Anticol = 3;</code>
     */
    tud.seemuh.nfcgate.network.c2c.C2C.Anticol getAnticol();
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.Anticol Anticol = 3;</code>
     */
    tud.seemuh.nfcgate.network.c2c.C2C.AnticolOrBuilder getAnticolOrBuilder();

    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.Status Status = 4;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.Status Status = 4;</code>
     */
    tud.seemuh.nfcgate.network.c2c.C2C.Status getStatus();
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.Status Status = 4;</code>
     */
    tud.seemuh.nfcgate.network.c2c.C2C.StatusOrBuilder getStatusOrBuilder();

    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2s.Data Data = 5;</code>
     */
    boolean hasData();
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2s.Data Data = 5;</code>
     */
    tud.seemuh.nfcgate.network.c2s.C2S.Data getData();
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2s.Data Data = 5;</code>
     */
    tud.seemuh.nfcgate.network.c2s.C2S.DataOrBuilder getDataOrBuilder();

    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2s.Session Session = 6;</code>
     */
    boolean hasSession();
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2s.Session Session = 6;</code>
     */
    tud.seemuh.nfcgate.network.c2s.C2S.Session getSession();
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2s.Session Session = 6;</code>
     */
    tud.seemuh.nfcgate.network.c2s.C2S.SessionOrBuilder getSessionOrBuilder();
  }
  /**
   * Protobuf type {@code tud.seemuh.nfcgate.network.meta.Wrapper}
   *
   * <pre>
   * Wrapper Message
   * This message contains another message
   * This is used to ensure that we only ever have to
   * expect one message type coming from the network
   * </pre>
   */
  public static final class Wrapper extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tud.seemuh.nfcgate.network.meta.Wrapper)
      WrapperOrBuilder {
    // Use Wrapper.newBuilder() to construct.
    private Wrapper(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Wrapper(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Wrapper defaultInstance;
    public static Wrapper getDefaultInstance() {
      return defaultInstance;
    }

    public Wrapper getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Wrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              tud.seemuh.nfcgate.network.c2c.C2C.NFCData.Builder subBuilder = null;
              if (messageCase_ == 2) {
                subBuilder = ((tud.seemuh.nfcgate.network.c2c.C2C.NFCData) message_).toBuilder();
              }
              message_ = input.readMessage(tud.seemuh.nfcgate.network.c2c.C2C.NFCData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((tud.seemuh.nfcgate.network.c2c.C2C.NFCData) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 2;
              break;
            }
            case 26: {
              tud.seemuh.nfcgate.network.c2c.C2C.Anticol.Builder subBuilder = null;
              if (messageCase_ == 3) {
                subBuilder = ((tud.seemuh.nfcgate.network.c2c.C2C.Anticol) message_).toBuilder();
              }
              message_ = input.readMessage(tud.seemuh.nfcgate.network.c2c.C2C.Anticol.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((tud.seemuh.nfcgate.network.c2c.C2C.Anticol) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 3;
              break;
            }
            case 34: {
              tud.seemuh.nfcgate.network.c2c.C2C.Status.Builder subBuilder = null;
              if (messageCase_ == 4) {
                subBuilder = ((tud.seemuh.nfcgate.network.c2c.C2C.Status) message_).toBuilder();
              }
              message_ = input.readMessage(tud.seemuh.nfcgate.network.c2c.C2C.Status.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((tud.seemuh.nfcgate.network.c2c.C2C.Status) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 4;
              break;
            }
            case 42: {
              tud.seemuh.nfcgate.network.c2s.C2S.Data.Builder subBuilder = null;
              if (messageCase_ == 5) {
                subBuilder = ((tud.seemuh.nfcgate.network.c2s.C2S.Data) message_).toBuilder();
              }
              message_ = input.readMessage(tud.seemuh.nfcgate.network.c2s.C2S.Data.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((tud.seemuh.nfcgate.network.c2s.C2S.Data) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 5;
              break;
            }
            case 50: {
              tud.seemuh.nfcgate.network.c2s.C2S.Session.Builder subBuilder = null;
              if (messageCase_ == 6) {
                subBuilder = ((tud.seemuh.nfcgate.network.c2s.C2S.Session) message_).toBuilder();
              }
              message_ = input.readMessage(tud.seemuh.nfcgate.network.c2s.C2S.Session.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((tud.seemuh.nfcgate.network.c2s.C2S.Session) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 6;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tud.seemuh.nfcgate.network.meta.MetaMessage.internal_static_tud_seemuh_nfcgate_network_meta_Wrapper_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tud.seemuh.nfcgate.network.meta.MetaMessage.internal_static_tud_seemuh_nfcgate_network_meta_Wrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper.class, tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper.Builder.class);
    }

    public static com.google.protobuf.Parser<Wrapper> PARSER =
        new com.google.protobuf.AbstractParser<Wrapper>() {
      public Wrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Wrapper(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Wrapper> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    private int messageCase_ = 0;
    private java.lang.Object message_;
    public enum MessageCase
        implements com.google.protobuf.Internal.EnumLite {
      NFCDATA(2),
      ANTICOL(3),
      STATUS(4),
      DATA(5),
      SESSION(6),
      MESSAGE_NOT_SET(0);
      private int value = 0;
      private MessageCase(int value) {
        this.value = value;
      }
      public static MessageCase valueOf(int value) {
        switch (value) {
          case 2: return NFCDATA;
          case 3: return ANTICOL;
          case 4: return STATUS;
          case 5: return DATA;
          case 6: return SESSION;
          case 0: return MESSAGE_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MessageCase
    getMessageCase() {
      return MessageCase.valueOf(
          messageCase_);
    }

    public static final int NFCDATA_FIELD_NUMBER = 2;
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData NFCData = 2;</code>
     */
    public boolean hasNFCData() {
      return messageCase_ == 2;
    }
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData NFCData = 2;</code>
     */
    public tud.seemuh.nfcgate.network.c2c.C2C.NFCData getNFCData() {
      if (messageCase_ == 2) {
         return (tud.seemuh.nfcgate.network.c2c.C2C.NFCData) message_;
      }
      return tud.seemuh.nfcgate.network.c2c.C2C.NFCData.getDefaultInstance();
    }
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData NFCData = 2;</code>
     */
    public tud.seemuh.nfcgate.network.c2c.C2C.NFCDataOrBuilder getNFCDataOrBuilder() {
      if (messageCase_ == 2) {
         return (tud.seemuh.nfcgate.network.c2c.C2C.NFCData) message_;
      }
      return tud.seemuh.nfcgate.network.c2c.C2C.NFCData.getDefaultInstance();
    }

    public static final int ANTICOL_FIELD_NUMBER = 3;
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.Anticol Anticol = 3;</code>
     */
    public boolean hasAnticol() {
      return messageCase_ == 3;
    }
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.Anticol Anticol = 3;</code>
     */
    public tud.seemuh.nfcgate.network.c2c.C2C.Anticol getAnticol() {
      if (messageCase_ == 3) {
         return (tud.seemuh.nfcgate.network.c2c.C2C.Anticol) message_;
      }
      return tud.seemuh.nfcgate.network.c2c.C2C.Anticol.getDefaultInstance();
    }
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.Anticol Anticol = 3;</code>
     */
    public tud.seemuh.nfcgate.network.c2c.C2C.AnticolOrBuilder getAnticolOrBuilder() {
      if (messageCase_ == 3) {
         return (tud.seemuh.nfcgate.network.c2c.C2C.Anticol) message_;
      }
      return tud.seemuh.nfcgate.network.c2c.C2C.Anticol.getDefaultInstance();
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.Status Status = 4;</code>
     */
    public boolean hasStatus() {
      return messageCase_ == 4;
    }
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.Status Status = 4;</code>
     */
    public tud.seemuh.nfcgate.network.c2c.C2C.Status getStatus() {
      if (messageCase_ == 4) {
         return (tud.seemuh.nfcgate.network.c2c.C2C.Status) message_;
      }
      return tud.seemuh.nfcgate.network.c2c.C2C.Status.getDefaultInstance();
    }
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.Status Status = 4;</code>
     */
    public tud.seemuh.nfcgate.network.c2c.C2C.StatusOrBuilder getStatusOrBuilder() {
      if (messageCase_ == 4) {
         return (tud.seemuh.nfcgate.network.c2c.C2C.Status) message_;
      }
      return tud.seemuh.nfcgate.network.c2c.C2C.Status.getDefaultInstance();
    }

    public static final int DATA_FIELD_NUMBER = 5;
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2s.Data Data = 5;</code>
     */
    public boolean hasData() {
      return messageCase_ == 5;
    }
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2s.Data Data = 5;</code>
     */
    public tud.seemuh.nfcgate.network.c2s.C2S.Data getData() {
      if (messageCase_ == 5) {
         return (tud.seemuh.nfcgate.network.c2s.C2S.Data) message_;
      }
      return tud.seemuh.nfcgate.network.c2s.C2S.Data.getDefaultInstance();
    }
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2s.Data Data = 5;</code>
     */
    public tud.seemuh.nfcgate.network.c2s.C2S.DataOrBuilder getDataOrBuilder() {
      if (messageCase_ == 5) {
         return (tud.seemuh.nfcgate.network.c2s.C2S.Data) message_;
      }
      return tud.seemuh.nfcgate.network.c2s.C2S.Data.getDefaultInstance();
    }

    public static final int SESSION_FIELD_NUMBER = 6;
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2s.Session Session = 6;</code>
     */
    public boolean hasSession() {
      return messageCase_ == 6;
    }
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2s.Session Session = 6;</code>
     */
    public tud.seemuh.nfcgate.network.c2s.C2S.Session getSession() {
      if (messageCase_ == 6) {
         return (tud.seemuh.nfcgate.network.c2s.C2S.Session) message_;
      }
      return tud.seemuh.nfcgate.network.c2s.C2S.Session.getDefaultInstance();
    }
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2s.Session Session = 6;</code>
     */
    public tud.seemuh.nfcgate.network.c2s.C2S.SessionOrBuilder getSessionOrBuilder() {
      if (messageCase_ == 6) {
         return (tud.seemuh.nfcgate.network.c2s.C2S.Session) message_;
      }
      return tud.seemuh.nfcgate.network.c2s.C2S.Session.getDefaultInstance();
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasNFCData()) {
        if (!getNFCData().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasAnticol()) {
        if (!getAnticol().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasStatus()) {
        if (!getStatus().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasData()) {
        if (!getData().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasSession()) {
        if (!getSession().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (messageCase_ == 2) {
        output.writeMessage(2, (tud.seemuh.nfcgate.network.c2c.C2C.NFCData) message_);
      }
      if (messageCase_ == 3) {
        output.writeMessage(3, (tud.seemuh.nfcgate.network.c2c.C2C.Anticol) message_);
      }
      if (messageCase_ == 4) {
        output.writeMessage(4, (tud.seemuh.nfcgate.network.c2c.C2C.Status) message_);
      }
      if (messageCase_ == 5) {
        output.writeMessage(5, (tud.seemuh.nfcgate.network.c2s.C2S.Data) message_);
      }
      if (messageCase_ == 6) {
        output.writeMessage(6, (tud.seemuh.nfcgate.network.c2s.C2S.Session) message_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (messageCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (tud.seemuh.nfcgate.network.c2c.C2C.NFCData) message_);
      }
      if (messageCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (tud.seemuh.nfcgate.network.c2c.C2C.Anticol) message_);
      }
      if (messageCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (tud.seemuh.nfcgate.network.c2c.C2C.Status) message_);
      }
      if (messageCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (tud.seemuh.nfcgate.network.c2s.C2S.Data) message_);
      }
      if (messageCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, (tud.seemuh.nfcgate.network.c2s.C2S.Session) message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tud.seemuh.nfcgate.network.meta.Wrapper}
     *
     * <pre>
     * Wrapper Message
     * This message contains another message
     * This is used to ensure that we only ever have to
     * expect one message type coming from the network
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tud.seemuh.nfcgate.network.meta.Wrapper)
        tud.seemuh.nfcgate.network.meta.MetaMessage.WrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.meta.MetaMessage.internal_static_tud_seemuh_nfcgate_network_meta_Wrapper_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tud.seemuh.nfcgate.network.meta.MetaMessage.internal_static_tud_seemuh_nfcgate_network_meta_Wrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper.class, tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper.Builder.class);
      }

      // Construct using tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageCase_ = 0;
        message_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tud.seemuh.nfcgate.network.meta.MetaMessage.internal_static_tud_seemuh_nfcgate_network_meta_Wrapper_descriptor;
      }

      public tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper getDefaultInstanceForType() {
        return tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper.getDefaultInstance();
      }

      public tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper build() {
        tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper buildPartial() {
        tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper result = new tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (messageCase_ == 2) {
          if (nFCDataBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = nFCDataBuilder_.build();
          }
        }
        if (messageCase_ == 3) {
          if (anticolBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = anticolBuilder_.build();
          }
        }
        if (messageCase_ == 4) {
          if (statusBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = statusBuilder_.build();
          }
        }
        if (messageCase_ == 5) {
          if (dataBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = dataBuilder_.build();
          }
        }
        if (messageCase_ == 6) {
          if (sessionBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = sessionBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.messageCase_ = messageCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper) {
          return mergeFrom((tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper other) {
        if (other == tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper.getDefaultInstance()) return this;
        switch (other.getMessageCase()) {
          case NFCDATA: {
            mergeNFCData(other.getNFCData());
            break;
          }
          case ANTICOL: {
            mergeAnticol(other.getAnticol());
            break;
          }
          case STATUS: {
            mergeStatus(other.getStatus());
            break;
          }
          case DATA: {
            mergeData(other.getData());
            break;
          }
          case SESSION: {
            mergeSession(other.getSession());
            break;
          }
          case MESSAGE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasNFCData()) {
          if (!getNFCData().isInitialized()) {
            
            return false;
          }
        }
        if (hasAnticol()) {
          if (!getAnticol().isInitialized()) {
            
            return false;
          }
        }
        if (hasStatus()) {
          if (!getStatus().isInitialized()) {
            
            return false;
          }
        }
        if (hasData()) {
          if (!getData().isInitialized()) {
            
            return false;
          }
        }
        if (hasSession()) {
          if (!getSession().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tud.seemuh.nfcgate.network.meta.MetaMessage.Wrapper) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int messageCase_ = 0;
      private java.lang.Object message_;
      public MessageCase
          getMessageCase() {
        return MessageCase.valueOf(
            messageCase_);
      }

      public Builder clearMessage() {
        messageCase_ = 0;
        message_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          tud.seemuh.nfcgate.network.c2c.C2C.NFCData, tud.seemuh.nfcgate.network.c2c.C2C.NFCData.Builder, tud.seemuh.nfcgate.network.c2c.C2C.NFCDataOrBuilder> nFCDataBuilder_;
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData NFCData = 2;</code>
       */
      public boolean hasNFCData() {
        return messageCase_ == 2;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData NFCData = 2;</code>
       */
      public tud.seemuh.nfcgate.network.c2c.C2C.NFCData getNFCData() {
        if (nFCDataBuilder_ == null) {
          if (messageCase_ == 2) {
            return (tud.seemuh.nfcgate.network.c2c.C2C.NFCData) message_;
          }
          return tud.seemuh.nfcgate.network.c2c.C2C.NFCData.getDefaultInstance();
        } else {
          if (messageCase_ == 2) {
            return nFCDataBuilder_.getMessage();
          }
          return tud.seemuh.nfcgate.network.c2c.C2C.NFCData.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData NFCData = 2;</code>
       */
      public Builder setNFCData(tud.seemuh.nfcgate.network.c2c.C2C.NFCData value) {
        if (nFCDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          nFCDataBuilder_.setMessage(value);
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData NFCData = 2;</code>
       */
      public Builder setNFCData(
          tud.seemuh.nfcgate.network.c2c.C2C.NFCData.Builder builderForValue) {
        if (nFCDataBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          nFCDataBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData NFCData = 2;</code>
       */
      public Builder mergeNFCData(tud.seemuh.nfcgate.network.c2c.C2C.NFCData value) {
        if (nFCDataBuilder_ == null) {
          if (messageCase_ == 2 &&
              message_ != tud.seemuh.nfcgate.network.c2c.C2C.NFCData.getDefaultInstance()) {
            message_ = tud.seemuh.nfcgate.network.c2c.C2C.NFCData.newBuilder((tud.seemuh.nfcgate.network.c2c.C2C.NFCData) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 2) {
            nFCDataBuilder_.mergeFrom(value);
          }
          nFCDataBuilder_.setMessage(value);
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData NFCData = 2;</code>
       */
      public Builder clearNFCData() {
        if (nFCDataBuilder_ == null) {
          if (messageCase_ == 2) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 2) {
            messageCase_ = 0;
            message_ = null;
          }
          nFCDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData NFCData = 2;</code>
       */
      public tud.seemuh.nfcgate.network.c2c.C2C.NFCData.Builder getNFCDataBuilder() {
        return getNFCDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData NFCData = 2;</code>
       */
      public tud.seemuh.nfcgate.network.c2c.C2C.NFCDataOrBuilder getNFCDataOrBuilder() {
        if ((messageCase_ == 2) && (nFCDataBuilder_ != null)) {
          return nFCDataBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 2) {
            return (tud.seemuh.nfcgate.network.c2c.C2C.NFCData) message_;
          }
          return tud.seemuh.nfcgate.network.c2c.C2C.NFCData.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData NFCData = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          tud.seemuh.nfcgate.network.c2c.C2C.NFCData, tud.seemuh.nfcgate.network.c2c.C2C.NFCData.Builder, tud.seemuh.nfcgate.network.c2c.C2C.NFCDataOrBuilder> 
          getNFCDataFieldBuilder() {
        if (nFCDataBuilder_ == null) {
          if (!(messageCase_ == 2)) {
            message_ = tud.seemuh.nfcgate.network.c2c.C2C.NFCData.getDefaultInstance();
          }
          nFCDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              tud.seemuh.nfcgate.network.c2c.C2C.NFCData, tud.seemuh.nfcgate.network.c2c.C2C.NFCData.Builder, tud.seemuh.nfcgate.network.c2c.C2C.NFCDataOrBuilder>(
                  (tud.seemuh.nfcgate.network.c2c.C2C.NFCData) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 2;
        return nFCDataBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          tud.seemuh.nfcgate.network.c2c.C2C.Anticol, tud.seemuh.nfcgate.network.c2c.C2C.Anticol.Builder, tud.seemuh.nfcgate.network.c2c.C2C.AnticolOrBuilder> anticolBuilder_;
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Anticol Anticol = 3;</code>
       */
      public boolean hasAnticol() {
        return messageCase_ == 3;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Anticol Anticol = 3;</code>
       */
      public tud.seemuh.nfcgate.network.c2c.C2C.Anticol getAnticol() {
        if (anticolBuilder_ == null) {
          if (messageCase_ == 3) {
            return (tud.seemuh.nfcgate.network.c2c.C2C.Anticol) message_;
          }
          return tud.seemuh.nfcgate.network.c2c.C2C.Anticol.getDefaultInstance();
        } else {
          if (messageCase_ == 3) {
            return anticolBuilder_.getMessage();
          }
          return tud.seemuh.nfcgate.network.c2c.C2C.Anticol.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Anticol Anticol = 3;</code>
       */
      public Builder setAnticol(tud.seemuh.nfcgate.network.c2c.C2C.Anticol value) {
        if (anticolBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          anticolBuilder_.setMessage(value);
        }
        messageCase_ = 3;
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Anticol Anticol = 3;</code>
       */
      public Builder setAnticol(
          tud.seemuh.nfcgate.network.c2c.C2C.Anticol.Builder builderForValue) {
        if (anticolBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          anticolBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 3;
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Anticol Anticol = 3;</code>
       */
      public Builder mergeAnticol(tud.seemuh.nfcgate.network.c2c.C2C.Anticol value) {
        if (anticolBuilder_ == null) {
          if (messageCase_ == 3 &&
              message_ != tud.seemuh.nfcgate.network.c2c.C2C.Anticol.getDefaultInstance()) {
            message_ = tud.seemuh.nfcgate.network.c2c.C2C.Anticol.newBuilder((tud.seemuh.nfcgate.network.c2c.C2C.Anticol) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 3) {
            anticolBuilder_.mergeFrom(value);
          }
          anticolBuilder_.setMessage(value);
        }
        messageCase_ = 3;
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Anticol Anticol = 3;</code>
       */
      public Builder clearAnticol() {
        if (anticolBuilder_ == null) {
          if (messageCase_ == 3) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 3) {
            messageCase_ = 0;
            message_ = null;
          }
          anticolBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Anticol Anticol = 3;</code>
       */
      public tud.seemuh.nfcgate.network.c2c.C2C.Anticol.Builder getAnticolBuilder() {
        return getAnticolFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Anticol Anticol = 3;</code>
       */
      public tud.seemuh.nfcgate.network.c2c.C2C.AnticolOrBuilder getAnticolOrBuilder() {
        if ((messageCase_ == 3) && (anticolBuilder_ != null)) {
          return anticolBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 3) {
            return (tud.seemuh.nfcgate.network.c2c.C2C.Anticol) message_;
          }
          return tud.seemuh.nfcgate.network.c2c.C2C.Anticol.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Anticol Anticol = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          tud.seemuh.nfcgate.network.c2c.C2C.Anticol, tud.seemuh.nfcgate.network.c2c.C2C.Anticol.Builder, tud.seemuh.nfcgate.network.c2c.C2C.AnticolOrBuilder> 
          getAnticolFieldBuilder() {
        if (anticolBuilder_ == null) {
          if (!(messageCase_ == 3)) {
            message_ = tud.seemuh.nfcgate.network.c2c.C2C.Anticol.getDefaultInstance();
          }
          anticolBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              tud.seemuh.nfcgate.network.c2c.C2C.Anticol, tud.seemuh.nfcgate.network.c2c.C2C.Anticol.Builder, tud.seemuh.nfcgate.network.c2c.C2C.AnticolOrBuilder>(
                  (tud.seemuh.nfcgate.network.c2c.C2C.Anticol) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 3;
        return anticolBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          tud.seemuh.nfcgate.network.c2c.C2C.Status, tud.seemuh.nfcgate.network.c2c.C2C.Status.Builder, tud.seemuh.nfcgate.network.c2c.C2C.StatusOrBuilder> statusBuilder_;
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Status Status = 4;</code>
       */
      public boolean hasStatus() {
        return messageCase_ == 4;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Status Status = 4;</code>
       */
      public tud.seemuh.nfcgate.network.c2c.C2C.Status getStatus() {
        if (statusBuilder_ == null) {
          if (messageCase_ == 4) {
            return (tud.seemuh.nfcgate.network.c2c.C2C.Status) message_;
          }
          return tud.seemuh.nfcgate.network.c2c.C2C.Status.getDefaultInstance();
        } else {
          if (messageCase_ == 4) {
            return statusBuilder_.getMessage();
          }
          return tud.seemuh.nfcgate.network.c2c.C2C.Status.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Status Status = 4;</code>
       */
      public Builder setStatus(tud.seemuh.nfcgate.network.c2c.C2C.Status value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          statusBuilder_.setMessage(value);
        }
        messageCase_ = 4;
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Status Status = 4;</code>
       */
      public Builder setStatus(
          tud.seemuh.nfcgate.network.c2c.C2C.Status.Builder builderForValue) {
        if (statusBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          statusBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 4;
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Status Status = 4;</code>
       */
      public Builder mergeStatus(tud.seemuh.nfcgate.network.c2c.C2C.Status value) {
        if (statusBuilder_ == null) {
          if (messageCase_ == 4 &&
              message_ != tud.seemuh.nfcgate.network.c2c.C2C.Status.getDefaultInstance()) {
            message_ = tud.seemuh.nfcgate.network.c2c.C2C.Status.newBuilder((tud.seemuh.nfcgate.network.c2c.C2C.Status) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 4) {
            statusBuilder_.mergeFrom(value);
          }
          statusBuilder_.setMessage(value);
        }
        messageCase_ = 4;
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Status Status = 4;</code>
       */
      public Builder clearStatus() {
        if (statusBuilder_ == null) {
          if (messageCase_ == 4) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 4) {
            messageCase_ = 0;
            message_ = null;
          }
          statusBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Status Status = 4;</code>
       */
      public tud.seemuh.nfcgate.network.c2c.C2C.Status.Builder getStatusBuilder() {
        return getStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Status Status = 4;</code>
       */
      public tud.seemuh.nfcgate.network.c2c.C2C.StatusOrBuilder getStatusOrBuilder() {
        if ((messageCase_ == 4) && (statusBuilder_ != null)) {
          return statusBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 4) {
            return (tud.seemuh.nfcgate.network.c2c.C2C.Status) message_;
          }
          return tud.seemuh.nfcgate.network.c2c.C2C.Status.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.Status Status = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          tud.seemuh.nfcgate.network.c2c.C2C.Status, tud.seemuh.nfcgate.network.c2c.C2C.Status.Builder, tud.seemuh.nfcgate.network.c2c.C2C.StatusOrBuilder> 
          getStatusFieldBuilder() {
        if (statusBuilder_ == null) {
          if (!(messageCase_ == 4)) {
            message_ = tud.seemuh.nfcgate.network.c2c.C2C.Status.getDefaultInstance();
          }
          statusBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              tud.seemuh.nfcgate.network.c2c.C2C.Status, tud.seemuh.nfcgate.network.c2c.C2C.Status.Builder, tud.seemuh.nfcgate.network.c2c.C2C.StatusOrBuilder>(
                  (tud.seemuh.nfcgate.network.c2c.C2C.Status) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 4;
        return statusBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          tud.seemuh.nfcgate.network.c2s.C2S.Data, tud.seemuh.nfcgate.network.c2s.C2S.Data.Builder, tud.seemuh.nfcgate.network.c2s.C2S.DataOrBuilder> dataBuilder_;
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Data Data = 5;</code>
       */
      public boolean hasData() {
        return messageCase_ == 5;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Data Data = 5;</code>
       */
      public tud.seemuh.nfcgate.network.c2s.C2S.Data getData() {
        if (dataBuilder_ == null) {
          if (messageCase_ == 5) {
            return (tud.seemuh.nfcgate.network.c2s.C2S.Data) message_;
          }
          return tud.seemuh.nfcgate.network.c2s.C2S.Data.getDefaultInstance();
        } else {
          if (messageCase_ == 5) {
            return dataBuilder_.getMessage();
          }
          return tud.seemuh.nfcgate.network.c2s.C2S.Data.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Data Data = 5;</code>
       */
      public Builder setData(tud.seemuh.nfcgate.network.c2s.C2S.Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }
        messageCase_ = 5;
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Data Data = 5;</code>
       */
      public Builder setData(
          tud.seemuh.nfcgate.network.c2s.C2S.Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 5;
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Data Data = 5;</code>
       */
      public Builder mergeData(tud.seemuh.nfcgate.network.c2s.C2S.Data value) {
        if (dataBuilder_ == null) {
          if (messageCase_ == 5 &&
              message_ != tud.seemuh.nfcgate.network.c2s.C2S.Data.getDefaultInstance()) {
            message_ = tud.seemuh.nfcgate.network.c2s.C2S.Data.newBuilder((tud.seemuh.nfcgate.network.c2s.C2S.Data) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 5) {
            dataBuilder_.mergeFrom(value);
          }
          dataBuilder_.setMessage(value);
        }
        messageCase_ = 5;
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Data Data = 5;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          if (messageCase_ == 5) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 5) {
            messageCase_ = 0;
            message_ = null;
          }
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Data Data = 5;</code>
       */
      public tud.seemuh.nfcgate.network.c2s.C2S.Data.Builder getDataBuilder() {
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Data Data = 5;</code>
       */
      public tud.seemuh.nfcgate.network.c2s.C2S.DataOrBuilder getDataOrBuilder() {
        if ((messageCase_ == 5) && (dataBuilder_ != null)) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 5) {
            return (tud.seemuh.nfcgate.network.c2s.C2S.Data) message_;
          }
          return tud.seemuh.nfcgate.network.c2s.C2S.Data.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Data Data = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          tud.seemuh.nfcgate.network.c2s.C2S.Data, tud.seemuh.nfcgate.network.c2s.C2S.Data.Builder, tud.seemuh.nfcgate.network.c2s.C2S.DataOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          if (!(messageCase_ == 5)) {
            message_ = tud.seemuh.nfcgate.network.c2s.C2S.Data.getDefaultInstance();
          }
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              tud.seemuh.nfcgate.network.c2s.C2S.Data, tud.seemuh.nfcgate.network.c2s.C2S.Data.Builder, tud.seemuh.nfcgate.network.c2s.C2S.DataOrBuilder>(
                  (tud.seemuh.nfcgate.network.c2s.C2S.Data) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 5;
        return dataBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          tud.seemuh.nfcgate.network.c2s.C2S.Session, tud.seemuh.nfcgate.network.c2s.C2S.Session.Builder, tud.seemuh.nfcgate.network.c2s.C2S.SessionOrBuilder> sessionBuilder_;
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Session Session = 6;</code>
       */
      public boolean hasSession() {
        return messageCase_ == 6;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Session Session = 6;</code>
       */
      public tud.seemuh.nfcgate.network.c2s.C2S.Session getSession() {
        if (sessionBuilder_ == null) {
          if (messageCase_ == 6) {
            return (tud.seemuh.nfcgate.network.c2s.C2S.Session) message_;
          }
          return tud.seemuh.nfcgate.network.c2s.C2S.Session.getDefaultInstance();
        } else {
          if (messageCase_ == 6) {
            return sessionBuilder_.getMessage();
          }
          return tud.seemuh.nfcgate.network.c2s.C2S.Session.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Session Session = 6;</code>
       */
      public Builder setSession(tud.seemuh.nfcgate.network.c2s.C2S.Session value) {
        if (sessionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          sessionBuilder_.setMessage(value);
        }
        messageCase_ = 6;
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Session Session = 6;</code>
       */
      public Builder setSession(
          tud.seemuh.nfcgate.network.c2s.C2S.Session.Builder builderForValue) {
        if (sessionBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          sessionBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 6;
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Session Session = 6;</code>
       */
      public Builder mergeSession(tud.seemuh.nfcgate.network.c2s.C2S.Session value) {
        if (sessionBuilder_ == null) {
          if (messageCase_ == 6 &&
              message_ != tud.seemuh.nfcgate.network.c2s.C2S.Session.getDefaultInstance()) {
            message_ = tud.seemuh.nfcgate.network.c2s.C2S.Session.newBuilder((tud.seemuh.nfcgate.network.c2s.C2S.Session) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 6) {
            sessionBuilder_.mergeFrom(value);
          }
          sessionBuilder_.setMessage(value);
        }
        messageCase_ = 6;
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Session Session = 6;</code>
       */
      public Builder clearSession() {
        if (sessionBuilder_ == null) {
          if (messageCase_ == 6) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 6) {
            messageCase_ = 0;
            message_ = null;
          }
          sessionBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Session Session = 6;</code>
       */
      public tud.seemuh.nfcgate.network.c2s.C2S.Session.Builder getSessionBuilder() {
        return getSessionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Session Session = 6;</code>
       */
      public tud.seemuh.nfcgate.network.c2s.C2S.SessionOrBuilder getSessionOrBuilder() {
        if ((messageCase_ == 6) && (sessionBuilder_ != null)) {
          return sessionBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 6) {
            return (tud.seemuh.nfcgate.network.c2s.C2S.Session) message_;
          }
          return tud.seemuh.nfcgate.network.c2s.C2S.Session.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2s.Session Session = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          tud.seemuh.nfcgate.network.c2s.C2S.Session, tud.seemuh.nfcgate.network.c2s.C2S.Session.Builder, tud.seemuh.nfcgate.network.c2s.C2S.SessionOrBuilder> 
          getSessionFieldBuilder() {
        if (sessionBuilder_ == null) {
          if (!(messageCase_ == 6)) {
            message_ = tud.seemuh.nfcgate.network.c2s.C2S.Session.getDefaultInstance();
          }
          sessionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              tud.seemuh.nfcgate.network.c2s.C2S.Session, tud.seemuh.nfcgate.network.c2s.C2S.Session.Builder, tud.seemuh.nfcgate.network.c2s.C2S.SessionOrBuilder>(
                  (tud.seemuh.nfcgate.network.c2s.C2S.Session) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 6;
        return sessionBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:tud.seemuh.nfcgate.network.meta.Wrapper)
    }

    static {
      defaultInstance = new Wrapper(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tud.seemuh.nfcgate.network.meta.Wrapper)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tud_seemuh_nfcgate_network_meta_Wrapper_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tud_seemuh_nfcgate_network_meta_Wrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021metaMessage.proto\022\037tud.seemuh.nfcgate." +
      "network.meta\032\tc2s.proto\032\tc2c.proto\"\270\002\n\007W" +
      "rapper\022:\n\007NFCData\030\002 \001(\0132\'.tud.seemuh.nfc" +
      "gate.network.c2c.NFCDataH\000\022:\n\007Anticol\030\003 " +
      "\001(\0132\'.tud.seemuh.nfcgate.network.c2c.Ant" +
      "icolH\000\0228\n\006Status\030\004 \001(\0132&.tud.seemuh.nfcg" +
      "ate.network.c2c.StatusH\000\0224\n\004Data\030\005 \001(\0132$" +
      ".tud.seemuh.nfcgate.network.c2s.DataH\000\022:" +
      "\n\007Session\030\006 \001(\0132\'.tud.seemuh.nfcgate.net" +
      "work.c2s.SessionH\000B\t\n\007message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tud.seemuh.nfcgate.network.c2s.C2S.getDescriptor(),
          tud.seemuh.nfcgate.network.c2c.C2C.getDescriptor(),
        }, assigner);
    internal_static_tud_seemuh_nfcgate_network_meta_Wrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tud_seemuh_nfcgate_network_meta_Wrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tud_seemuh_nfcgate_network_meta_Wrapper_descriptor,
        new java.lang.String[] { "NFCData", "Anticol", "Status", "Data", "Session", "Message", });
    tud.seemuh.nfcgate.network.c2s.C2S.getDescriptor();
    tud.seemuh.nfcgate.network.c2c.C2C.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
