// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: c2c.proto

package tud.seemuh.nfcgate.network.c2c;

public final class C2C {
  private C2C() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KexOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tud.seemuh.nfcgate.network.c2c.Kex)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .tud.seemuh.nfcgate.network.c2c.Kex.CryptoAlgorithm algorithm = 1;</code>
     *
     * <pre>
     * Crypto Algorithm
     * Signifies which crypto Algorithm is used
     * </pre>
     */
    boolean hasAlgorithm();
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2c.Kex.CryptoAlgorithm algorithm = 1;</code>
     *
     * <pre>
     * Crypto Algorithm
     * Signifies which crypto Algorithm is used
     * </pre>
     */
    tud.seemuh.nfcgate.network.c2c.C2C.Kex.CryptoAlgorithm getAlgorithm();

    /**
     * <code>required bytes crypto_message = 2;</code>
     *
     * <pre>
     * Crypto Message
     * The actual bytes needed for the crypto exchange
     * </pre>
     */
    boolean hasCryptoMessage();
    /**
     * <code>required bytes crypto_message = 2;</code>
     *
     * <pre>
     * Crypto Message
     * The actual bytes needed for the crypto exchange
     * </pre>
     */
    com.google.protobuf.ByteString getCryptoMessage();
  }
  /**
   * Protobuf type {@code tud.seemuh.nfcgate.network.c2c.Kex}
   *
   * <pre>
   * Key Exchange Message
   * Message for performing cryptographic key exchanges
   * </pre>
   */
  public static final class Kex extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tud.seemuh.nfcgate.network.c2c.Kex)
      KexOrBuilder {
    // Use Kex.newBuilder() to construct.
    private Kex(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Kex(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Kex defaultInstance;
    public static Kex getDefaultInstance() {
      return defaultInstance;
    }

    public Kex getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Kex(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              tud.seemuh.nfcgate.network.c2c.C2C.Kex.CryptoAlgorithm value = tud.seemuh.nfcgate.network.c2c.C2C.Kex.CryptoAlgorithm.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                algorithm_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              cryptoMessage_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Kex_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Kex_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tud.seemuh.nfcgate.network.c2c.C2C.Kex.class, tud.seemuh.nfcgate.network.c2c.C2C.Kex.Builder.class);
    }

    public static com.google.protobuf.Parser<Kex> PARSER =
        new com.google.protobuf.AbstractParser<Kex>() {
      public Kex parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Kex(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Kex> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code tud.seemuh.nfcgate.network.c2c.Kex.CryptoAlgorithm}
     */
    public enum CryptoAlgorithm
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DHE_RSA_AES256 = 0;</code>
       *
       * <pre>
       * TODO Does this make sense?
       * </pre>
       */
      DHE_RSA_AES256(0, 0),
      ;

      /**
       * <code>DHE_RSA_AES256 = 0;</code>
       *
       * <pre>
       * TODO Does this make sense?
       * </pre>
       */
      public static final int DHE_RSA_AES256_VALUE = 0;


      public final int getNumber() { return value; }

      public static CryptoAlgorithm valueOf(int value) {
        switch (value) {
          case 0: return DHE_RSA_AES256;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CryptoAlgorithm>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CryptoAlgorithm>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CryptoAlgorithm>() {
              public CryptoAlgorithm findValueByNumber(int number) {
                return CryptoAlgorithm.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.c2c.C2C.Kex.getDescriptor().getEnumTypes().get(0);
      }

      private static final CryptoAlgorithm[] VALUES = values();

      public static CryptoAlgorithm valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CryptoAlgorithm(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tud.seemuh.nfcgate.network.c2c.Kex.CryptoAlgorithm)
    }

    private int bitField0_;
    public static final int ALGORITHM_FIELD_NUMBER = 1;
    private tud.seemuh.nfcgate.network.c2c.C2C.Kex.CryptoAlgorithm algorithm_;
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2c.Kex.CryptoAlgorithm algorithm = 1;</code>
     *
     * <pre>
     * Crypto Algorithm
     * Signifies which crypto Algorithm is used
     * </pre>
     */
    public boolean hasAlgorithm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2c.Kex.CryptoAlgorithm algorithm = 1;</code>
     *
     * <pre>
     * Crypto Algorithm
     * Signifies which crypto Algorithm is used
     * </pre>
     */
    public tud.seemuh.nfcgate.network.c2c.C2C.Kex.CryptoAlgorithm getAlgorithm() {
      return algorithm_;
    }

    public static final int CRYPTO_MESSAGE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString cryptoMessage_;
    /**
     * <code>required bytes crypto_message = 2;</code>
     *
     * <pre>
     * Crypto Message
     * The actual bytes needed for the crypto exchange
     * </pre>
     */
    public boolean hasCryptoMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes crypto_message = 2;</code>
     *
     * <pre>
     * Crypto Message
     * The actual bytes needed for the crypto exchange
     * </pre>
     */
    public com.google.protobuf.ByteString getCryptoMessage() {
      return cryptoMessage_;
    }

    private void initFields() {
      algorithm_ = tud.seemuh.nfcgate.network.c2c.C2C.Kex.CryptoAlgorithm.DHE_RSA_AES256;
      cryptoMessage_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAlgorithm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCryptoMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, algorithm_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, cryptoMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, algorithm_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, cryptoMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static tud.seemuh.nfcgate.network.c2c.C2C.Kex parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Kex parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Kex parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Kex parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Kex parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Kex parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Kex parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Kex parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Kex parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Kex parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tud.seemuh.nfcgate.network.c2c.C2C.Kex prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tud.seemuh.nfcgate.network.c2c.Kex}
     *
     * <pre>
     * Key Exchange Message
     * Message for performing cryptographic key exchanges
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tud.seemuh.nfcgate.network.c2c.Kex)
        tud.seemuh.nfcgate.network.c2c.C2C.KexOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Kex_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Kex_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tud.seemuh.nfcgate.network.c2c.C2C.Kex.class, tud.seemuh.nfcgate.network.c2c.C2C.Kex.Builder.class);
      }

      // Construct using tud.seemuh.nfcgate.network.c2c.C2C.Kex.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        algorithm_ = tud.seemuh.nfcgate.network.c2c.C2C.Kex.CryptoAlgorithm.DHE_RSA_AES256;
        bitField0_ = (bitField0_ & ~0x00000001);
        cryptoMessage_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Kex_descriptor;
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.Kex getDefaultInstanceForType() {
        return tud.seemuh.nfcgate.network.c2c.C2C.Kex.getDefaultInstance();
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.Kex build() {
        tud.seemuh.nfcgate.network.c2c.C2C.Kex result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.Kex buildPartial() {
        tud.seemuh.nfcgate.network.c2c.C2C.Kex result = new tud.seemuh.nfcgate.network.c2c.C2C.Kex(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.algorithm_ = algorithm_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cryptoMessage_ = cryptoMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tud.seemuh.nfcgate.network.c2c.C2C.Kex) {
          return mergeFrom((tud.seemuh.nfcgate.network.c2c.C2C.Kex)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tud.seemuh.nfcgate.network.c2c.C2C.Kex other) {
        if (other == tud.seemuh.nfcgate.network.c2c.C2C.Kex.getDefaultInstance()) return this;
        if (other.hasAlgorithm()) {
          setAlgorithm(other.getAlgorithm());
        }
        if (other.hasCryptoMessage()) {
          setCryptoMessage(other.getCryptoMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAlgorithm()) {
          
          return false;
        }
        if (!hasCryptoMessage()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tud.seemuh.nfcgate.network.c2c.C2C.Kex parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tud.seemuh.nfcgate.network.c2c.C2C.Kex) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private tud.seemuh.nfcgate.network.c2c.C2C.Kex.CryptoAlgorithm algorithm_ = tud.seemuh.nfcgate.network.c2c.C2C.Kex.CryptoAlgorithm.DHE_RSA_AES256;
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2c.Kex.CryptoAlgorithm algorithm = 1;</code>
       *
       * <pre>
       * Crypto Algorithm
       * Signifies which crypto Algorithm is used
       * </pre>
       */
      public boolean hasAlgorithm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2c.Kex.CryptoAlgorithm algorithm = 1;</code>
       *
       * <pre>
       * Crypto Algorithm
       * Signifies which crypto Algorithm is used
       * </pre>
       */
      public tud.seemuh.nfcgate.network.c2c.C2C.Kex.CryptoAlgorithm getAlgorithm() {
        return algorithm_;
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2c.Kex.CryptoAlgorithm algorithm = 1;</code>
       *
       * <pre>
       * Crypto Algorithm
       * Signifies which crypto Algorithm is used
       * </pre>
       */
      public Builder setAlgorithm(tud.seemuh.nfcgate.network.c2c.C2C.Kex.CryptoAlgorithm value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        algorithm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2c.Kex.CryptoAlgorithm algorithm = 1;</code>
       *
       * <pre>
       * Crypto Algorithm
       * Signifies which crypto Algorithm is used
       * </pre>
       */
      public Builder clearAlgorithm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        algorithm_ = tud.seemuh.nfcgate.network.c2c.C2C.Kex.CryptoAlgorithm.DHE_RSA_AES256;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString cryptoMessage_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes crypto_message = 2;</code>
       *
       * <pre>
       * Crypto Message
       * The actual bytes needed for the crypto exchange
       * </pre>
       */
      public boolean hasCryptoMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes crypto_message = 2;</code>
       *
       * <pre>
       * Crypto Message
       * The actual bytes needed for the crypto exchange
       * </pre>
       */
      public com.google.protobuf.ByteString getCryptoMessage() {
        return cryptoMessage_;
      }
      /**
       * <code>required bytes crypto_message = 2;</code>
       *
       * <pre>
       * Crypto Message
       * The actual bytes needed for the crypto exchange
       * </pre>
       */
      public Builder setCryptoMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cryptoMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes crypto_message = 2;</code>
       *
       * <pre>
       * Crypto Message
       * The actual bytes needed for the crypto exchange
       * </pre>
       */
      public Builder clearCryptoMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cryptoMessage_ = getDefaultInstance().getCryptoMessage();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tud.seemuh.nfcgate.network.c2c.Kex)
    }

    static {
      defaultInstance = new Kex(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tud.seemuh.nfcgate.network.c2c.Kex)
  }

  public interface NFCDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tud.seemuh.nfcgate.network.c2c.NFCData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .tud.seemuh.nfcgate.network.c2c.NFCData.DataSource data_source = 1;</code>
     *
     * <pre>
     * Data Source
     * Signifies if this data is coming from a NFC Card
     * or a NFC Reader
     * </pre>
     */
    boolean hasDataSource();
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2c.NFCData.DataSource data_source = 1;</code>
     *
     * <pre>
     * Data Source
     * Signifies if this data is coming from a NFC Card
     * or a NFC Reader
     * </pre>
     */
    tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource getDataSource();

    /**
     * <code>required bytes data_bytes = 2;</code>
     *
     * <pre>
     * Data bytes
     * The actual bytes to be sent
     * </pre>
     */
    boolean hasDataBytes();
    /**
     * <code>required bytes data_bytes = 2;</code>
     *
     * <pre>
     * Data bytes
     * The actual bytes to be sent
     * </pre>
     */
    com.google.protobuf.ByteString getDataBytes();

    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData.NFCDataErrorCode errcode = 3 [default = ERROR_NOERROR];</code>
     *
     * <pre>
     * Error Code
     * Error code of the last received message operation
     * </pre>
     */
    boolean hasErrcode();
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData.NFCDataErrorCode errcode = 3 [default = ERROR_NOERROR];</code>
     *
     * <pre>
     * Error Code
     * Error code of the last received message operation
     * </pre>
     */
    tud.seemuh.nfcgate.network.c2c.C2C.NFCData.NFCDataErrorCode getErrcode();
  }
  /**
   * Protobuf type {@code tud.seemuh.nfcgate.network.c2c.NFCData}
   *
   * <pre>
   * NFC Data message
   * Message for passing NFC data between clients
   * </pre>
   */
  public static final class NFCData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tud.seemuh.nfcgate.network.c2c.NFCData)
      NFCDataOrBuilder {
    // Use NFCData.newBuilder() to construct.
    private NFCData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NFCData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NFCData defaultInstance;
    public static NFCData getDefaultInstance() {
      return defaultInstance;
    }

    public NFCData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NFCData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource value = tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                dataSource_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              dataBytes_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              tud.seemuh.nfcgate.network.c2c.C2C.NFCData.NFCDataErrorCode value = tud.seemuh.nfcgate.network.c2c.C2C.NFCData.NFCDataErrorCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                errcode_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tud.seemuh.nfcgate.network.c2c.C2C.NFCData.class, tud.seemuh.nfcgate.network.c2c.C2C.NFCData.Builder.class);
    }

    public static com.google.protobuf.Parser<NFCData> PARSER =
        new com.google.protobuf.AbstractParser<NFCData>() {
      public NFCData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NFCData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NFCData> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code tud.seemuh.nfcgate.network.c2c.NFCData.DataSource}
     */
    public enum DataSource
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>READER = 0;</code>
       */
      READER(0, 0),
      /**
       * <code>CARD = 1;</code>
       */
      CARD(1, 1),
      ;

      /**
       * <code>READER = 0;</code>
       */
      public static final int READER_VALUE = 0;
      /**
       * <code>CARD = 1;</code>
       */
      public static final int CARD_VALUE = 1;


      public final int getNumber() { return value; }

      public static DataSource valueOf(int value) {
        switch (value) {
          case 0: return READER;
          case 1: return CARD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataSource>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<DataSource>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataSource>() {
              public DataSource findValueByNumber(int number) {
                return DataSource.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.c2c.C2C.NFCData.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataSource[] VALUES = values();

      public static DataSource valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private DataSource(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tud.seemuh.nfcgate.network.c2c.NFCData.DataSource)
    }

    /**
     * Protobuf enum {@code tud.seemuh.nfcgate.network.c2c.NFCData.NFCDataErrorCode}
     */
    public enum NFCDataErrorCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ERROR_NOERROR = 0;</code>
       */
      ERROR_NOERROR(0, 0),
      /**
       * <code>ERROR_NO_NFC_CONN = 1;</code>
       */
      ERROR_NO_NFC_CONN(1, 1),
      /**
       * <code>ERROR_UNKNOWN = 3;</code>
       */
      ERROR_UNKNOWN(2, 3),
      ;

      /**
       * <code>ERROR_NOERROR = 0;</code>
       */
      public static final int ERROR_NOERROR_VALUE = 0;
      /**
       * <code>ERROR_NO_NFC_CONN = 1;</code>
       */
      public static final int ERROR_NO_NFC_CONN_VALUE = 1;
      /**
       * <code>ERROR_UNKNOWN = 3;</code>
       */
      public static final int ERROR_UNKNOWN_VALUE = 3;


      public final int getNumber() { return value; }

      public static NFCDataErrorCode valueOf(int value) {
        switch (value) {
          case 0: return ERROR_NOERROR;
          case 1: return ERROR_NO_NFC_CONN;
          case 3: return ERROR_UNKNOWN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NFCDataErrorCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<NFCDataErrorCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NFCDataErrorCode>() {
              public NFCDataErrorCode findValueByNumber(int number) {
                return NFCDataErrorCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.c2c.C2C.NFCData.getDescriptor().getEnumTypes().get(1);
      }

      private static final NFCDataErrorCode[] VALUES = values();

      public static NFCDataErrorCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private NFCDataErrorCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tud.seemuh.nfcgate.network.c2c.NFCData.NFCDataErrorCode)
    }

    private int bitField0_;
    public static final int DATA_SOURCE_FIELD_NUMBER = 1;
    private tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource dataSource_;
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2c.NFCData.DataSource data_source = 1;</code>
     *
     * <pre>
     * Data Source
     * Signifies if this data is coming from a NFC Card
     * or a NFC Reader
     * </pre>
     */
    public boolean hasDataSource() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2c.NFCData.DataSource data_source = 1;</code>
     *
     * <pre>
     * Data Source
     * Signifies if this data is coming from a NFC Card
     * or a NFC Reader
     * </pre>
     */
    public tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource getDataSource() {
      return dataSource_;
    }

    public static final int DATA_BYTES_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString dataBytes_;
    /**
     * <code>required bytes data_bytes = 2;</code>
     *
     * <pre>
     * Data bytes
     * The actual bytes to be sent
     * </pre>
     */
    public boolean hasDataBytes() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes data_bytes = 2;</code>
     *
     * <pre>
     * Data bytes
     * The actual bytes to be sent
     * </pre>
     */
    public com.google.protobuf.ByteString getDataBytes() {
      return dataBytes_;
    }

    public static final int ERRCODE_FIELD_NUMBER = 3;
    private tud.seemuh.nfcgate.network.c2c.C2C.NFCData.NFCDataErrorCode errcode_;
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData.NFCDataErrorCode errcode = 3 [default = ERROR_NOERROR];</code>
     *
     * <pre>
     * Error Code
     * Error code of the last received message operation
     * </pre>
     */
    public boolean hasErrcode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData.NFCDataErrorCode errcode = 3 [default = ERROR_NOERROR];</code>
     *
     * <pre>
     * Error Code
     * Error code of the last received message operation
     * </pre>
     */
    public tud.seemuh.nfcgate.network.c2c.C2C.NFCData.NFCDataErrorCode getErrcode() {
      return errcode_;
    }

    private void initFields() {
      dataSource_ = tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource.READER;
      dataBytes_ = com.google.protobuf.ByteString.EMPTY;
      errcode_ = tud.seemuh.nfcgate.network.c2c.C2C.NFCData.NFCDataErrorCode.ERROR_NOERROR;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDataSource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataBytes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, dataSource_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, dataBytes_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, errcode_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataSource_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, dataBytes_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, errcode_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tud.seemuh.nfcgate.network.c2c.C2C.NFCData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tud.seemuh.nfcgate.network.c2c.NFCData}
     *
     * <pre>
     * NFC Data message
     * Message for passing NFC data between clients
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tud.seemuh.nfcgate.network.c2c.NFCData)
        tud.seemuh.nfcgate.network.c2c.C2C.NFCDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tud.seemuh.nfcgate.network.c2c.C2C.NFCData.class, tud.seemuh.nfcgate.network.c2c.C2C.NFCData.Builder.class);
      }

      // Construct using tud.seemuh.nfcgate.network.c2c.C2C.NFCData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        dataSource_ = tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource.READER;
        bitField0_ = (bitField0_ & ~0x00000001);
        dataBytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        errcode_ = tud.seemuh.nfcgate.network.c2c.C2C.NFCData.NFCDataErrorCode.ERROR_NOERROR;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_descriptor;
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.NFCData getDefaultInstanceForType() {
        return tud.seemuh.nfcgate.network.c2c.C2C.NFCData.getDefaultInstance();
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.NFCData build() {
        tud.seemuh.nfcgate.network.c2c.C2C.NFCData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.NFCData buildPartial() {
        tud.seemuh.nfcgate.network.c2c.C2C.NFCData result = new tud.seemuh.nfcgate.network.c2c.C2C.NFCData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dataSource_ = dataSource_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dataBytes_ = dataBytes_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errcode_ = errcode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tud.seemuh.nfcgate.network.c2c.C2C.NFCData) {
          return mergeFrom((tud.seemuh.nfcgate.network.c2c.C2C.NFCData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tud.seemuh.nfcgate.network.c2c.C2C.NFCData other) {
        if (other == tud.seemuh.nfcgate.network.c2c.C2C.NFCData.getDefaultInstance()) return this;
        if (other.hasDataSource()) {
          setDataSource(other.getDataSource());
        }
        if (other.hasDataBytes()) {
          setDataBytes(other.getDataBytes());
        }
        if (other.hasErrcode()) {
          setErrcode(other.getErrcode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDataSource()) {
          
          return false;
        }
        if (!hasDataBytes()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tud.seemuh.nfcgate.network.c2c.C2C.NFCData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tud.seemuh.nfcgate.network.c2c.C2C.NFCData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource dataSource_ = tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource.READER;
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2c.NFCData.DataSource data_source = 1;</code>
       *
       * <pre>
       * Data Source
       * Signifies if this data is coming from a NFC Card
       * or a NFC Reader
       * </pre>
       */
      public boolean hasDataSource() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2c.NFCData.DataSource data_source = 1;</code>
       *
       * <pre>
       * Data Source
       * Signifies if this data is coming from a NFC Card
       * or a NFC Reader
       * </pre>
       */
      public tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource getDataSource() {
        return dataSource_;
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2c.NFCData.DataSource data_source = 1;</code>
       *
       * <pre>
       * Data Source
       * Signifies if this data is coming from a NFC Card
       * or a NFC Reader
       * </pre>
       */
      public Builder setDataSource(tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        dataSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2c.NFCData.DataSource data_source = 1;</code>
       *
       * <pre>
       * Data Source
       * Signifies if this data is coming from a NFC Card
       * or a NFC Reader
       * </pre>
       */
      public Builder clearDataSource() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dataSource_ = tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource.READER;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString dataBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data_bytes = 2;</code>
       *
       * <pre>
       * Data bytes
       * The actual bytes to be sent
       * </pre>
       */
      public boolean hasDataBytes() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes data_bytes = 2;</code>
       *
       * <pre>
       * Data bytes
       * The actual bytes to be sent
       * </pre>
       */
      public com.google.protobuf.ByteString getDataBytes() {
        return dataBytes_;
      }
      /**
       * <code>required bytes data_bytes = 2;</code>
       *
       * <pre>
       * Data bytes
       * The actual bytes to be sent
       * </pre>
       */
      public Builder setDataBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dataBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data_bytes = 2;</code>
       *
       * <pre>
       * Data bytes
       * The actual bytes to be sent
       * </pre>
       */
      public Builder clearDataBytes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dataBytes_ = getDefaultInstance().getDataBytes();
        onChanged();
        return this;
      }

      private tud.seemuh.nfcgate.network.c2c.C2C.NFCData.NFCDataErrorCode errcode_ = tud.seemuh.nfcgate.network.c2c.C2C.NFCData.NFCDataErrorCode.ERROR_NOERROR;
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData.NFCDataErrorCode errcode = 3 [default = ERROR_NOERROR];</code>
       *
       * <pre>
       * Error Code
       * Error code of the last received message operation
       * </pre>
       */
      public boolean hasErrcode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData.NFCDataErrorCode errcode = 3 [default = ERROR_NOERROR];</code>
       *
       * <pre>
       * Error Code
       * Error code of the last received message operation
       * </pre>
       */
      public tud.seemuh.nfcgate.network.c2c.C2C.NFCData.NFCDataErrorCode getErrcode() {
        return errcode_;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData.NFCDataErrorCode errcode = 3 [default = ERROR_NOERROR];</code>
       *
       * <pre>
       * Error Code
       * Error code of the last received message operation
       * </pre>
       */
      public Builder setErrcode(tud.seemuh.nfcgate.network.c2c.C2C.NFCData.NFCDataErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        errcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .tud.seemuh.nfcgate.network.c2c.NFCData.NFCDataErrorCode errcode = 3 [default = ERROR_NOERROR];</code>
       *
       * <pre>
       * Error Code
       * Error code of the last received message operation
       * </pre>
       */
      public Builder clearErrcode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errcode_ = tud.seemuh.nfcgate.network.c2c.C2C.NFCData.NFCDataErrorCode.ERROR_NOERROR;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tud.seemuh.nfcgate.network.c2c.NFCData)
    }

    static {
      defaultInstance = new NFCData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tud.seemuh.nfcgate.network.c2c.NFCData)
  }

  public interface StatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tud.seemuh.nfcgate.network.c2c.Status)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .tud.seemuh.nfcgate.network.c2c.Status.StatusCode code = 1;</code>
     *
     * <pre>
     * Status Code
     * The status code to be communicated
     * </pre>
     */
    boolean hasCode();
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2c.Status.StatusCode code = 1;</code>
     *
     * <pre>
     * Status Code
     * The status code to be communicated
     * </pre>
     */
    tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode getCode();
  }
  /**
   * Protobuf type {@code tud.seemuh.nfcgate.network.c2c.Status}
   *
   * <pre>
   * Status Messages
   * Messages for communicating status changes
   * </pre>
   */
  public static final class Status extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tud.seemuh.nfcgate.network.c2c.Status)
      StatusOrBuilder {
    // Use Status.newBuilder() to construct.
    private Status(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Status(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Status defaultInstance;
    public static Status getDefaultInstance() {
      return defaultInstance;
    }

    public Status getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Status(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode value = tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                code_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Status_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Status_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tud.seemuh.nfcgate.network.c2c.C2C.Status.class, tud.seemuh.nfcgate.network.c2c.C2C.Status.Builder.class);
    }

    public static com.google.protobuf.Parser<Status> PARSER =
        new com.google.protobuf.AbstractParser<Status>() {
      public Status parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Status(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Status> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code tud.seemuh.nfcgate.network.c2c.Status.StatusCode}
     */
    public enum StatusCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>KEEPALIVE = 0;</code>
       */
      KEEPALIVE(0, 0),
      /**
       * <code>CARD_FOUND = 1;</code>
       */
      CARD_FOUND(1, 1),
      /**
       * <code>CARD_REMOVED = 2;</code>
       */
      CARD_REMOVED(2, 2),
      /**
       * <code>READER_FOUND = 3;</code>
       */
      READER_FOUND(3, 3),
      /**
       * <code>READER_REMOVED = 4;</code>
       */
      READER_REMOVED(4, 4),
      /**
       * <code>NFC_NO_CONN = 5;</code>
       */
      NFC_NO_CONN(5, 5),
      /**
       * <code>INVALID_MSG_FMT = 6;</code>
       */
      INVALID_MSG_FMT(6, 6),
      /**
       * <code>NOT_IMPLEMENTED = 7;</code>
       */
      NOT_IMPLEMENTED(7, 7),
      /**
       * <code>UNKNOWN_MESSAGE = 8;</code>
       */
      UNKNOWN_MESSAGE(8, 8),
      /**
       * <code>UNKNOWN_ERROR = 9;</code>
       */
      UNKNOWN_ERROR(9, 9),
      ;

      /**
       * <code>KEEPALIVE = 0;</code>
       */
      public static final int KEEPALIVE_VALUE = 0;
      /**
       * <code>CARD_FOUND = 1;</code>
       */
      public static final int CARD_FOUND_VALUE = 1;
      /**
       * <code>CARD_REMOVED = 2;</code>
       */
      public static final int CARD_REMOVED_VALUE = 2;
      /**
       * <code>READER_FOUND = 3;</code>
       */
      public static final int READER_FOUND_VALUE = 3;
      /**
       * <code>READER_REMOVED = 4;</code>
       */
      public static final int READER_REMOVED_VALUE = 4;
      /**
       * <code>NFC_NO_CONN = 5;</code>
       */
      public static final int NFC_NO_CONN_VALUE = 5;
      /**
       * <code>INVALID_MSG_FMT = 6;</code>
       */
      public static final int INVALID_MSG_FMT_VALUE = 6;
      /**
       * <code>NOT_IMPLEMENTED = 7;</code>
       */
      public static final int NOT_IMPLEMENTED_VALUE = 7;
      /**
       * <code>UNKNOWN_MESSAGE = 8;</code>
       */
      public static final int UNKNOWN_MESSAGE_VALUE = 8;
      /**
       * <code>UNKNOWN_ERROR = 9;</code>
       */
      public static final int UNKNOWN_ERROR_VALUE = 9;


      public final int getNumber() { return value; }

      public static StatusCode valueOf(int value) {
        switch (value) {
          case 0: return KEEPALIVE;
          case 1: return CARD_FOUND;
          case 2: return CARD_REMOVED;
          case 3: return READER_FOUND;
          case 4: return READER_REMOVED;
          case 5: return NFC_NO_CONN;
          case 6: return INVALID_MSG_FMT;
          case 7: return NOT_IMPLEMENTED;
          case 8: return UNKNOWN_MESSAGE;
          case 9: return UNKNOWN_ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StatusCode>() {
              public StatusCode findValueByNumber(int number) {
                return StatusCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.c2c.C2C.Status.getDescriptor().getEnumTypes().get(0);
      }

      private static final StatusCode[] VALUES = values();

      public static StatusCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private StatusCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tud.seemuh.nfcgate.network.c2c.Status.StatusCode)
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode code_;
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2c.Status.StatusCode code = 1;</code>
     *
     * <pre>
     * Status Code
     * The status code to be communicated
     * </pre>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2c.Status.StatusCode code = 1;</code>
     *
     * <pre>
     * Status Code
     * The status code to be communicated
     * </pre>
     */
    public tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode getCode() {
      return code_;
    }

    private void initFields() {
      code_ = tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode.KEEPALIVE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, code_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tud.seemuh.nfcgate.network.c2c.C2C.Status prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tud.seemuh.nfcgate.network.c2c.Status}
     *
     * <pre>
     * Status Messages
     * Messages for communicating status changes
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tud.seemuh.nfcgate.network.c2c.Status)
        tud.seemuh.nfcgate.network.c2c.C2C.StatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Status_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Status_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tud.seemuh.nfcgate.network.c2c.C2C.Status.class, tud.seemuh.nfcgate.network.c2c.C2C.Status.Builder.class);
      }

      // Construct using tud.seemuh.nfcgate.network.c2c.C2C.Status.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode.KEEPALIVE;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Status_descriptor;
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.Status getDefaultInstanceForType() {
        return tud.seemuh.nfcgate.network.c2c.C2C.Status.getDefaultInstance();
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.Status build() {
        tud.seemuh.nfcgate.network.c2c.C2C.Status result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.Status buildPartial() {
        tud.seemuh.nfcgate.network.c2c.C2C.Status result = new tud.seemuh.nfcgate.network.c2c.C2C.Status(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tud.seemuh.nfcgate.network.c2c.C2C.Status) {
          return mergeFrom((tud.seemuh.nfcgate.network.c2c.C2C.Status)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tud.seemuh.nfcgate.network.c2c.C2C.Status other) {
        if (other == tud.seemuh.nfcgate.network.c2c.C2C.Status.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tud.seemuh.nfcgate.network.c2c.C2C.Status parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tud.seemuh.nfcgate.network.c2c.C2C.Status) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode code_ = tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode.KEEPALIVE;
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2c.Status.StatusCode code = 1;</code>
       *
       * <pre>
       * Status Code
       * The status code to be communicated
       * </pre>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2c.Status.StatusCode code = 1;</code>
       *
       * <pre>
       * Status Code
       * The status code to be communicated
       * </pre>
       */
      public tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode getCode() {
        return code_;
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2c.Status.StatusCode code = 1;</code>
       *
       * <pre>
       * Status Code
       * The status code to be communicated
       * </pre>
       */
      public Builder setCode(tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2c.Status.StatusCode code = 1;</code>
       *
       * <pre>
       * Status Code
       * The status code to be communicated
       * </pre>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode.KEEPALIVE;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tud.seemuh.nfcgate.network.c2c.Status)
    }

    static {
      defaultInstance = new Status(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tud.seemuh.nfcgate.network.c2c.Status)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tud_seemuh_nfcgate_network_c2c_Kex_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tud_seemuh_nfcgate_network_c2c_Kex_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tud_seemuh_nfcgate_network_c2c_Status_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tud_seemuh_nfcgate_network_c2c_Status_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tc2c.proto\022\036tud.seemuh.nfcgate.network." +
      "c2c\"\214\001\n\003Kex\022F\n\talgorithm\030\001 \002(\01623.tud.see" +
      "muh.nfcgate.network.c2c.Kex.CryptoAlgori" +
      "thm\022\026\n\016crypto_message\030\002 \002(\014\"%\n\017CryptoAlg" +
      "orithm\022\022\n\016DHE_RSA_AES256\020\000\"\265\002\n\007NFCData\022G" +
      "\n\013data_source\030\001 \002(\01622.tud.seemuh.nfcgate" +
      ".network.c2c.NFCData.DataSource\022\022\n\ndata_" +
      "bytes\030\002 \002(\014\022X\n\007errcode\030\003 \001(\01628.tud.seemu" +
      "h.nfcgate.network.c2c.NFCData.NFCDataErr" +
      "orCode:\rERROR_NOERROR\"\"\n\nDataSource\022\n\n\006R",
      "EADER\020\000\022\010\n\004CARD\020\001\"O\n\020NFCDataErrorCode\022\021\n" +
      "\rERROR_NOERROR\020\000\022\025\n\021ERROR_NO_NFC_CONN\020\001\022" +
      "\021\n\rERROR_UNKNOWN\020\003\"\222\002\n\006Status\022?\n\004code\030\001 " +
      "\002(\01621.tud.seemuh.nfcgate.network.c2c.Sta" +
      "tus.StatusCode\"\306\001\n\nStatusCode\022\r\n\tKEEPALI" +
      "VE\020\000\022\016\n\nCARD_FOUND\020\001\022\020\n\014CARD_REMOVED\020\002\022\020" +
      "\n\014READER_FOUND\020\003\022\022\n\016READER_REMOVED\020\004\022\017\n\013" +
      "NFC_NO_CONN\020\005\022\023\n\017INVALID_MSG_FMT\020\006\022\023\n\017NO" +
      "T_IMPLEMENTED\020\007\022\023\n\017UNKNOWN_MESSAGE\020\010\022\021\n\r" +
      "UNKNOWN_ERROR\020\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tud_seemuh_nfcgate_network_c2c_Kex_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tud_seemuh_nfcgate_network_c2c_Kex_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tud_seemuh_nfcgate_network_c2c_Kex_descriptor,
        new java.lang.String[] { "Algorithm", "CryptoMessage", });
    internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_descriptor,
        new java.lang.String[] { "DataSource", "DataBytes", "Errcode", });
    internal_static_tud_seemuh_nfcgate_network_c2c_Status_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tud_seemuh_nfcgate_network_c2c_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tud_seemuh_nfcgate_network_c2c_Status_descriptor,
        new java.lang.String[] { "Code", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
