// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: c2c.proto

package tud.seemuh.nfcgate.network.c2c;

public final class C2C {
  private C2C() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NFCDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tud.seemuh.nfcgate.network.c2c.NFCData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Data Source
     * Signifies if this data is coming from a NFC Card
     * or a NFC Reader
     * </pre>
     *
     * <code>required .tud.seemuh.nfcgate.network.c2c.NFCData.DataSource data_source = 1;</code>
     */
    boolean hasDataSource();
    /**
     * <pre>
     * Data Source
     * Signifies if this data is coming from a NFC Card
     * or a NFC Reader
     * </pre>
     *
     * <code>required .tud.seemuh.nfcgate.network.c2c.NFCData.DataSource data_source = 1;</code>
     */
    tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource getDataSource();

    /**
     * <pre>
     * Data bytes
     * The actual bytes to be sent
     * </pre>
     *
     * <code>required bytes data_bytes = 2;</code>
     */
    boolean hasDataBytes();
    /**
     * <pre>
     * Data bytes
     * The actual bytes to be sent
     * </pre>
     *
     * <code>required bytes data_bytes = 2;</code>
     */
    com.google.protobuf.ByteString getDataBytes();
  }
  /**
   * <pre>
   * NFC Data message
   * Message for passing NFC data between clients
   * </pre>
   *
   * Protobuf type {@code tud.seemuh.nfcgate.network.c2c.NFCData}
   */
  public  static final class NFCData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tud.seemuh.nfcgate.network.c2c.NFCData)
      NFCDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NFCData.newBuilder() to construct.
    private NFCData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NFCData() {
      dataSource_ = 0;
      dataBytes_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NFCData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource value = tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                dataSource_ = rawValue;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              dataBytes_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tud.seemuh.nfcgate.network.c2c.C2C.NFCData.class, tud.seemuh.nfcgate.network.c2c.C2C.NFCData.Builder.class);
    }

    /**
     * Protobuf enum {@code tud.seemuh.nfcgate.network.c2c.NFCData.DataSource}
     */
    public enum DataSource
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>READER = 0;</code>
       */
      READER(0),
      /**
       * <code>CARD = 1;</code>
       */
      CARD(1),
      ;

      /**
       * <code>READER = 0;</code>
       */
      public static final int READER_VALUE = 0;
      /**
       * <code>CARD = 1;</code>
       */
      public static final int CARD_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataSource valueOf(int value) {
        return forNumber(value);
      }

      public static DataSource forNumber(int value) {
        switch (value) {
          case 0: return READER;
          case 1: return CARD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataSource>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataSource> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataSource>() {
              public DataSource findValueByNumber(int number) {
                return DataSource.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.c2c.C2C.NFCData.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataSource[] VALUES = values();

      public static DataSource valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataSource(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tud.seemuh.nfcgate.network.c2c.NFCData.DataSource)
    }

    private int bitField0_;
    public static final int DATA_SOURCE_FIELD_NUMBER = 1;
    private int dataSource_;
    /**
     * <pre>
     * Data Source
     * Signifies if this data is coming from a NFC Card
     * or a NFC Reader
     * </pre>
     *
     * <code>required .tud.seemuh.nfcgate.network.c2c.NFCData.DataSource data_source = 1;</code>
     */
    public boolean hasDataSource() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * Data Source
     * Signifies if this data is coming from a NFC Card
     * or a NFC Reader
     * </pre>
     *
     * <code>required .tud.seemuh.nfcgate.network.c2c.NFCData.DataSource data_source = 1;</code>
     */
    public tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource getDataSource() {
      tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource result = tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource.valueOf(dataSource_);
      return result == null ? tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource.READER : result;
    }

    public static final int DATA_BYTES_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString dataBytes_;
    /**
     * <pre>
     * Data bytes
     * The actual bytes to be sent
     * </pre>
     *
     * <code>required bytes data_bytes = 2;</code>
     */
    public boolean hasDataBytes() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * Data bytes
     * The actual bytes to be sent
     * </pre>
     *
     * <code>required bytes data_bytes = 2;</code>
     */
    public com.google.protobuf.ByteString getDataBytes() {
      return dataBytes_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDataSource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataBytes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, dataSource_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, dataBytes_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataSource_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, dataBytes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tud.seemuh.nfcgate.network.c2c.C2C.NFCData)) {
        return super.equals(obj);
      }
      tud.seemuh.nfcgate.network.c2c.C2C.NFCData other = (tud.seemuh.nfcgate.network.c2c.C2C.NFCData) obj;

      boolean result = true;
      result = result && (hasDataSource() == other.hasDataSource());
      if (hasDataSource()) {
        result = result && dataSource_ == other.dataSource_;
      }
      result = result && (hasDataBytes() == other.hasDataBytes());
      if (hasDataBytes()) {
        result = result && getDataBytes()
            .equals(other.getDataBytes());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDataSource()) {
        hash = (37 * hash) + DATA_SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + dataSource_;
      }
      if (hasDataBytes()) {
        hash = (37 * hash) + DATA_BYTES_FIELD_NUMBER;
        hash = (53 * hash) + getDataBytes().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tud.seemuh.nfcgate.network.c2c.C2C.NFCData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * NFC Data message
     * Message for passing NFC data between clients
     * </pre>
     *
     * Protobuf type {@code tud.seemuh.nfcgate.network.c2c.NFCData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tud.seemuh.nfcgate.network.c2c.NFCData)
        tud.seemuh.nfcgate.network.c2c.C2C.NFCDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tud.seemuh.nfcgate.network.c2c.C2C.NFCData.class, tud.seemuh.nfcgate.network.c2c.C2C.NFCData.Builder.class);
      }

      // Construct using tud.seemuh.nfcgate.network.c2c.C2C.NFCData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        dataSource_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        dataBytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_descriptor;
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.NFCData getDefaultInstanceForType() {
        return tud.seemuh.nfcgate.network.c2c.C2C.NFCData.getDefaultInstance();
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.NFCData build() {
        tud.seemuh.nfcgate.network.c2c.C2C.NFCData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.NFCData buildPartial() {
        tud.seemuh.nfcgate.network.c2c.C2C.NFCData result = new tud.seemuh.nfcgate.network.c2c.C2C.NFCData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dataSource_ = dataSource_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dataBytes_ = dataBytes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tud.seemuh.nfcgate.network.c2c.C2C.NFCData) {
          return mergeFrom((tud.seemuh.nfcgate.network.c2c.C2C.NFCData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tud.seemuh.nfcgate.network.c2c.C2C.NFCData other) {
        if (other == tud.seemuh.nfcgate.network.c2c.C2C.NFCData.getDefaultInstance()) return this;
        if (other.hasDataSource()) {
          setDataSource(other.getDataSource());
        }
        if (other.hasDataBytes()) {
          setDataBytes(other.getDataBytes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDataSource()) {
          return false;
        }
        if (!hasDataBytes()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tud.seemuh.nfcgate.network.c2c.C2C.NFCData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tud.seemuh.nfcgate.network.c2c.C2C.NFCData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int dataSource_ = 0;
      /**
       * <pre>
       * Data Source
       * Signifies if this data is coming from a NFC Card
       * or a NFC Reader
       * </pre>
       *
       * <code>required .tud.seemuh.nfcgate.network.c2c.NFCData.DataSource data_source = 1;</code>
       */
      public boolean hasDataSource() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * Data Source
       * Signifies if this data is coming from a NFC Card
       * or a NFC Reader
       * </pre>
       *
       * <code>required .tud.seemuh.nfcgate.network.c2c.NFCData.DataSource data_source = 1;</code>
       */
      public tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource getDataSource() {
        tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource result = tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource.valueOf(dataSource_);
        return result == null ? tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource.READER : result;
      }
      /**
       * <pre>
       * Data Source
       * Signifies if this data is coming from a NFC Card
       * or a NFC Reader
       * </pre>
       *
       * <code>required .tud.seemuh.nfcgate.network.c2c.NFCData.DataSource data_source = 1;</code>
       */
      public Builder setDataSource(tud.seemuh.nfcgate.network.c2c.C2C.NFCData.DataSource value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        dataSource_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Data Source
       * Signifies if this data is coming from a NFC Card
       * or a NFC Reader
       * </pre>
       *
       * <code>required .tud.seemuh.nfcgate.network.c2c.NFCData.DataSource data_source = 1;</code>
       */
      public Builder clearDataSource() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dataSource_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString dataBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Data bytes
       * The actual bytes to be sent
       * </pre>
       *
       * <code>required bytes data_bytes = 2;</code>
       */
      public boolean hasDataBytes() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * Data bytes
       * The actual bytes to be sent
       * </pre>
       *
       * <code>required bytes data_bytes = 2;</code>
       */
      public com.google.protobuf.ByteString getDataBytes() {
        return dataBytes_;
      }
      /**
       * <pre>
       * Data bytes
       * The actual bytes to be sent
       * </pre>
       *
       * <code>required bytes data_bytes = 2;</code>
       */
      public Builder setDataBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dataBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Data bytes
       * The actual bytes to be sent
       * </pre>
       *
       * <code>required bytes data_bytes = 2;</code>
       */
      public Builder clearDataBytes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dataBytes_ = getDefaultInstance().getDataBytes();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tud.seemuh.nfcgate.network.c2c.NFCData)
    }

    // @@protoc_insertion_point(class_scope:tud.seemuh.nfcgate.network.c2c.NFCData)
    private static final tud.seemuh.nfcgate.network.c2c.C2C.NFCData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tud.seemuh.nfcgate.network.c2c.C2C.NFCData();
    }

    public static tud.seemuh.nfcgate.network.c2c.C2C.NFCData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NFCData>
        PARSER = new com.google.protobuf.AbstractParser<NFCData>() {
      public NFCData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NFCData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NFCData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NFCData> getParserForType() {
      return PARSER;
    }

    public tud.seemuh.nfcgate.network.c2c.C2C.NFCData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AnticolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tud.seemuh.nfcgate.network.c2c.Anticol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes CONFIG = 1;</code>
     */
    boolean hasCONFIG();
    /**
     * <code>required bytes CONFIG = 1;</code>
     */
    com.google.protobuf.ByteString getCONFIG();
  }
  /**
   * <pre>
   * Anticollision messages
   * Message for transmitting NFC config
   * </pre>
   *
   * Protobuf type {@code tud.seemuh.nfcgate.network.c2c.Anticol}
   */
  public  static final class Anticol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tud.seemuh.nfcgate.network.c2c.Anticol)
      AnticolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Anticol.newBuilder() to construct.
    private Anticol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Anticol() {
      cONFIG_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Anticol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              cONFIG_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Anticol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Anticol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tud.seemuh.nfcgate.network.c2c.C2C.Anticol.class, tud.seemuh.nfcgate.network.c2c.C2C.Anticol.Builder.class);
    }

    private int bitField0_;
    public static final int CONFIG_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString cONFIG_;
    /**
     * <code>required bytes CONFIG = 1;</code>
     */
    public boolean hasCONFIG() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes CONFIG = 1;</code>
     */
    public com.google.protobuf.ByteString getCONFIG() {
      return cONFIG_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCONFIG()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, cONFIG_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, cONFIG_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tud.seemuh.nfcgate.network.c2c.C2C.Anticol)) {
        return super.equals(obj);
      }
      tud.seemuh.nfcgate.network.c2c.C2C.Anticol other = (tud.seemuh.nfcgate.network.c2c.C2C.Anticol) obj;

      boolean result = true;
      result = result && (hasCONFIG() == other.hasCONFIG());
      if (hasCONFIG()) {
        result = result && getCONFIG()
            .equals(other.getCONFIG());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCONFIG()) {
        hash = (37 * hash) + CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getCONFIG().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tud.seemuh.nfcgate.network.c2c.C2C.Anticol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Anticol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Anticol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Anticol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Anticol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Anticol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Anticol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Anticol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Anticol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Anticol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Anticol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Anticol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tud.seemuh.nfcgate.network.c2c.C2C.Anticol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Anticollision messages
     * Message for transmitting NFC config
     * </pre>
     *
     * Protobuf type {@code tud.seemuh.nfcgate.network.c2c.Anticol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tud.seemuh.nfcgate.network.c2c.Anticol)
        tud.seemuh.nfcgate.network.c2c.C2C.AnticolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Anticol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Anticol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tud.seemuh.nfcgate.network.c2c.C2C.Anticol.class, tud.seemuh.nfcgate.network.c2c.C2C.Anticol.Builder.class);
      }

      // Construct using tud.seemuh.nfcgate.network.c2c.C2C.Anticol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cONFIG_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Anticol_descriptor;
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.Anticol getDefaultInstanceForType() {
        return tud.seemuh.nfcgate.network.c2c.C2C.Anticol.getDefaultInstance();
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.Anticol build() {
        tud.seemuh.nfcgate.network.c2c.C2C.Anticol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.Anticol buildPartial() {
        tud.seemuh.nfcgate.network.c2c.C2C.Anticol result = new tud.seemuh.nfcgate.network.c2c.C2C.Anticol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cONFIG_ = cONFIG_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tud.seemuh.nfcgate.network.c2c.C2C.Anticol) {
          return mergeFrom((tud.seemuh.nfcgate.network.c2c.C2C.Anticol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tud.seemuh.nfcgate.network.c2c.C2C.Anticol other) {
        if (other == tud.seemuh.nfcgate.network.c2c.C2C.Anticol.getDefaultInstance()) return this;
        if (other.hasCONFIG()) {
          setCONFIG(other.getCONFIG());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCONFIG()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tud.seemuh.nfcgate.network.c2c.C2C.Anticol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tud.seemuh.nfcgate.network.c2c.C2C.Anticol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString cONFIG_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes CONFIG = 1;</code>
       */
      public boolean hasCONFIG() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes CONFIG = 1;</code>
       */
      public com.google.protobuf.ByteString getCONFIG() {
        return cONFIG_;
      }
      /**
       * <code>required bytes CONFIG = 1;</code>
       */
      public Builder setCONFIG(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cONFIG_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes CONFIG = 1;</code>
       */
      public Builder clearCONFIG() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cONFIG_ = getDefaultInstance().getCONFIG();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tud.seemuh.nfcgate.network.c2c.Anticol)
    }

    // @@protoc_insertion_point(class_scope:tud.seemuh.nfcgate.network.c2c.Anticol)
    private static final tud.seemuh.nfcgate.network.c2c.C2C.Anticol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tud.seemuh.nfcgate.network.c2c.C2C.Anticol();
    }

    public static tud.seemuh.nfcgate.network.c2c.C2C.Anticol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Anticol>
        PARSER = new com.google.protobuf.AbstractParser<Anticol>() {
      public Anticol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Anticol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Anticol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Anticol> getParserForType() {
      return PARSER;
    }

    public tud.seemuh.nfcgate.network.c2c.C2C.Anticol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tud.seemuh.nfcgate.network.c2c.Status)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Status Code
     * The status code to be communicated
     * </pre>
     *
     * <code>required .tud.seemuh.nfcgate.network.c2c.Status.StatusCode code = 1;</code>
     */
    boolean hasCode();
    /**
     * <pre>
     * Status Code
     * The status code to be communicated
     * </pre>
     *
     * <code>required .tud.seemuh.nfcgate.network.c2c.Status.StatusCode code = 1;</code>
     */
    tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode getCode();
  }
  /**
   * <pre>
   * Status Messages
   * Messages for communicating status changes
   * </pre>
   *
   * Protobuf type {@code tud.seemuh.nfcgate.network.c2c.Status}
   */
  public  static final class Status extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tud.seemuh.nfcgate.network.c2c.Status)
      StatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Status.newBuilder() to construct.
    private Status(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Status() {
      code_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Status(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode value = tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                code_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Status_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Status_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tud.seemuh.nfcgate.network.c2c.C2C.Status.class, tud.seemuh.nfcgate.network.c2c.C2C.Status.Builder.class);
    }

    /**
     * Protobuf enum {@code tud.seemuh.nfcgate.network.c2c.Status.StatusCode}
     */
    public enum StatusCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>KEEPALIVE_REQ = 0;</code>
       */
      KEEPALIVE_REQ(0),
      /**
       * <code>KEEPALIVE_REP = 1;</code>
       */
      KEEPALIVE_REP(1),
      /**
       * <code>CARD_FOUND = 2;</code>
       */
      CARD_FOUND(2),
      /**
       * <code>CARD_REMOVED = 3;</code>
       */
      CARD_REMOVED(3),
      /**
       * <code>READER_FOUND = 4;</code>
       */
      READER_FOUND(4),
      /**
       * <code>READER_REMOVED = 5;</code>
       */
      READER_REMOVED(5),
      /**
       * <code>NFC_NO_CONN = 6;</code>
       */
      NFC_NO_CONN(6),
      /**
       * <code>INVALID_MSG_FMT = 7;</code>
       */
      INVALID_MSG_FMT(7),
      /**
       * <code>NOT_IMPLEMENTED = 8;</code>
       */
      NOT_IMPLEMENTED(8),
      /**
       * <code>UNKNOWN_MESSAGE = 9;</code>
       */
      UNKNOWN_MESSAGE(9),
      /**
       * <code>UNKNOWN_ERROR = 10;</code>
       */
      UNKNOWN_ERROR(10),
      ;

      /**
       * <code>KEEPALIVE_REQ = 0;</code>
       */
      public static final int KEEPALIVE_REQ_VALUE = 0;
      /**
       * <code>KEEPALIVE_REP = 1;</code>
       */
      public static final int KEEPALIVE_REP_VALUE = 1;
      /**
       * <code>CARD_FOUND = 2;</code>
       */
      public static final int CARD_FOUND_VALUE = 2;
      /**
       * <code>CARD_REMOVED = 3;</code>
       */
      public static final int CARD_REMOVED_VALUE = 3;
      /**
       * <code>READER_FOUND = 4;</code>
       */
      public static final int READER_FOUND_VALUE = 4;
      /**
       * <code>READER_REMOVED = 5;</code>
       */
      public static final int READER_REMOVED_VALUE = 5;
      /**
       * <code>NFC_NO_CONN = 6;</code>
       */
      public static final int NFC_NO_CONN_VALUE = 6;
      /**
       * <code>INVALID_MSG_FMT = 7;</code>
       */
      public static final int INVALID_MSG_FMT_VALUE = 7;
      /**
       * <code>NOT_IMPLEMENTED = 8;</code>
       */
      public static final int NOT_IMPLEMENTED_VALUE = 8;
      /**
       * <code>UNKNOWN_MESSAGE = 9;</code>
       */
      public static final int UNKNOWN_MESSAGE_VALUE = 9;
      /**
       * <code>UNKNOWN_ERROR = 10;</code>
       */
      public static final int UNKNOWN_ERROR_VALUE = 10;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static StatusCode valueOf(int value) {
        return forNumber(value);
      }

      public static StatusCode forNumber(int value) {
        switch (value) {
          case 0: return KEEPALIVE_REQ;
          case 1: return KEEPALIVE_REP;
          case 2: return CARD_FOUND;
          case 3: return CARD_REMOVED;
          case 4: return READER_FOUND;
          case 5: return READER_REMOVED;
          case 6: return NFC_NO_CONN;
          case 7: return INVALID_MSG_FMT;
          case 8: return NOT_IMPLEMENTED;
          case 9: return UNKNOWN_MESSAGE;
          case 10: return UNKNOWN_ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          StatusCode> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StatusCode>() {
              public StatusCode findValueByNumber(int number) {
                return StatusCode.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.c2c.C2C.Status.getDescriptor().getEnumTypes().get(0);
      }

      private static final StatusCode[] VALUES = values();

      public static StatusCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private StatusCode(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tud.seemuh.nfcgate.network.c2c.Status.StatusCode)
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <pre>
     * Status Code
     * The status code to be communicated
     * </pre>
     *
     * <code>required .tud.seemuh.nfcgate.network.c2c.Status.StatusCode code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * Status Code
     * The status code to be communicated
     * </pre>
     *
     * <code>required .tud.seemuh.nfcgate.network.c2c.Status.StatusCode code = 1;</code>
     */
    public tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode getCode() {
      tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode result = tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode.valueOf(code_);
      return result == null ? tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode.KEEPALIVE_REQ : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, code_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tud.seemuh.nfcgate.network.c2c.C2C.Status)) {
        return super.equals(obj);
      }
      tud.seemuh.nfcgate.network.c2c.C2C.Status other = (tud.seemuh.nfcgate.network.c2c.C2C.Status) obj;

      boolean result = true;
      result = result && (hasCode() == other.hasCode());
      if (hasCode()) {
        result = result && code_ == other.code_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + code_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tud.seemuh.nfcgate.network.c2c.C2C.Status parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tud.seemuh.nfcgate.network.c2c.C2C.Status prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Status Messages
     * Messages for communicating status changes
     * </pre>
     *
     * Protobuf type {@code tud.seemuh.nfcgate.network.c2c.Status}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tud.seemuh.nfcgate.network.c2c.Status)
        tud.seemuh.nfcgate.network.c2c.C2C.StatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Status_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Status_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tud.seemuh.nfcgate.network.c2c.C2C.Status.class, tud.seemuh.nfcgate.network.c2c.C2C.Status.Builder.class);
      }

      // Construct using tud.seemuh.nfcgate.network.c2c.C2C.Status.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tud.seemuh.nfcgate.network.c2c.C2C.internal_static_tud_seemuh_nfcgate_network_c2c_Status_descriptor;
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.Status getDefaultInstanceForType() {
        return tud.seemuh.nfcgate.network.c2c.C2C.Status.getDefaultInstance();
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.Status build() {
        tud.seemuh.nfcgate.network.c2c.C2C.Status result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tud.seemuh.nfcgate.network.c2c.C2C.Status buildPartial() {
        tud.seemuh.nfcgate.network.c2c.C2C.Status result = new tud.seemuh.nfcgate.network.c2c.C2C.Status(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tud.seemuh.nfcgate.network.c2c.C2C.Status) {
          return mergeFrom((tud.seemuh.nfcgate.network.c2c.C2C.Status)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tud.seemuh.nfcgate.network.c2c.C2C.Status other) {
        if (other == tud.seemuh.nfcgate.network.c2c.C2C.Status.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCode()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tud.seemuh.nfcgate.network.c2c.C2C.Status parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tud.seemuh.nfcgate.network.c2c.C2C.Status) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int code_ = 0;
      /**
       * <pre>
       * Status Code
       * The status code to be communicated
       * </pre>
       *
       * <code>required .tud.seemuh.nfcgate.network.c2c.Status.StatusCode code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * Status Code
       * The status code to be communicated
       * </pre>
       *
       * <code>required .tud.seemuh.nfcgate.network.c2c.Status.StatusCode code = 1;</code>
       */
      public tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode getCode() {
        tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode result = tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode.valueOf(code_);
        return result == null ? tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode.KEEPALIVE_REQ : result;
      }
      /**
       * <pre>
       * Status Code
       * The status code to be communicated
       * </pre>
       *
       * <code>required .tud.seemuh.nfcgate.network.c2c.Status.StatusCode code = 1;</code>
       */
      public Builder setCode(tud.seemuh.nfcgate.network.c2c.C2C.Status.StatusCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        code_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Status Code
       * The status code to be communicated
       * </pre>
       *
       * <code>required .tud.seemuh.nfcgate.network.c2c.Status.StatusCode code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tud.seemuh.nfcgate.network.c2c.Status)
    }

    // @@protoc_insertion_point(class_scope:tud.seemuh.nfcgate.network.c2c.Status)
    private static final tud.seemuh.nfcgate.network.c2c.C2C.Status DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tud.seemuh.nfcgate.network.c2c.C2C.Status();
    }

    public static tud.seemuh.nfcgate.network.c2c.C2C.Status getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Status>
        PARSER = new com.google.protobuf.AbstractParser<Status>() {
      public Status parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Status(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Status> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Status> getParserForType() {
      return PARSER;
    }

    public tud.seemuh.nfcgate.network.c2c.C2C.Status getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tud_seemuh_nfcgate_network_c2c_Anticol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tud_seemuh_nfcgate_network_c2c_Anticol_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tud_seemuh_nfcgate_network_c2c_Status_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tud_seemuh_nfcgate_network_c2c_Status_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tc2c.proto\022\036tud.seemuh.nfcgate.network." +
      "c2c\"\212\001\n\007NFCData\022G\n\013data_source\030\001 \002(\01622.t" +
      "ud.seemuh.nfcgate.network.c2c.NFCData.Da" +
      "taSource\022\022\n\ndata_bytes\030\002 \002(\014\"\"\n\nDataSour" +
      "ce\022\n\n\006READER\020\000\022\010\n\004CARD\020\001\"\031\n\007Anticol\022\016\n\006C" +
      "ONFIG\030\001 \002(\014\"\251\002\n\006Status\022?\n\004code\030\001 \002(\01621.t" +
      "ud.seemuh.nfcgate.network.c2c.Status.Sta" +
      "tusCode\"\335\001\n\nStatusCode\022\021\n\rKEEPALIVE_REQ\020" +
      "\000\022\021\n\rKEEPALIVE_REP\020\001\022\016\n\nCARD_FOUND\020\002\022\020\n\014" +
      "CARD_REMOVED\020\003\022\020\n\014READER_FOUND\020\004\022\022\n\016READ" +
      "ER_REMOVED\020\005\022\017\n\013NFC_NO_CONN\020\006\022\023\n\017INVALID" +
      "_MSG_FMT\020\007\022\023\n\017NOT_IMPLEMENTED\020\010\022\023\n\017UNKNO" +
      "WN_MESSAGE\020\t\022\021\n\rUNKNOWN_ERROR\020\n"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tud_seemuh_nfcgate_network_c2c_NFCData_descriptor,
        new java.lang.String[] { "DataSource", "DataBytes", });
    internal_static_tud_seemuh_nfcgate_network_c2c_Anticol_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tud_seemuh_nfcgate_network_c2c_Anticol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tud_seemuh_nfcgate_network_c2c_Anticol_descriptor,
        new java.lang.String[] { "CONFIG", });
    internal_static_tud_seemuh_nfcgate_network_c2c_Status_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tud_seemuh_nfcgate_network_c2c_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tud_seemuh_nfcgate_network_c2c_Status_descriptor,
        new java.lang.String[] { "Code", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
