// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: c2s.proto

package tud.seemuh.nfcgate.network.c2s;

public final class C2S {
  private C2S() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SessionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tud.seemuh.nfcgate.network.c2s.Session)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .tud.seemuh.nfcgate.network.c2s.Session.SessionOpcode opcode = 1;</code>
     *
     * <pre>
     * Opcode
     * describes intent of the message
     * </pre>
     */
    boolean hasOpcode();
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2s.Session.SessionOpcode opcode = 1;</code>
     *
     * <pre>
     * Opcode
     * describes intent of the message
     * </pre>
     */
    tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionOpcode getOpcode();

    /**
     * <code>optional string session_secret = 2;</code>
     *
     * <pre>
     * Session secret
     * Set by server on SESSION_CREATE_SUCCESS
     * Required for SESSION_JOIN, SESSION_LEAVE
     * </pre>
     */
    boolean hasSessionSecret();
    /**
     * <code>optional string session_secret = 2;</code>
     *
     * <pre>
     * Session secret
     * Set by server on SESSION_CREATE_SUCCESS
     * Required for SESSION_JOIN, SESSION_LEAVE
     * </pre>
     */
    java.lang.String getSessionSecret();
    /**
     * <code>optional string session_secret = 2;</code>
     *
     * <pre>
     * Session secret
     * Set by server on SESSION_CREATE_SUCCESS
     * Required for SESSION_JOIN, SESSION_LEAVE
     * </pre>
     */
    com.google.protobuf.ByteString
        getSessionSecretBytes();

    /**
     * <code>required .tud.seemuh.nfcgate.network.c2s.Session.SessionErrorCode errcode = 3 [default = ERROR_NOERROR];</code>
     *
     * <pre>
     * Error code
     * Set by server on every message
     * Defaults to ERROR_NOERROR
     * </pre>
     */
    boolean hasErrcode();
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2s.Session.SessionErrorCode errcode = 3 [default = ERROR_NOERROR];</code>
     *
     * <pre>
     * Error code
     * Set by server on every message
     * Defaults to ERROR_NOERROR
     * </pre>
     */
    tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionErrorCode getErrcode();
  }
  /**
   * Protobuf type {@code tud.seemuh.nfcgate.network.c2s.Session}
   *
   * <pre>
   * Session management messages
   * </pre>
   */
  public static final class Session extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tud.seemuh.nfcgate.network.c2s.Session)
      SessionOrBuilder {
    // Use Session.newBuilder() to construct.
    private Session(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Session(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Session defaultInstance;
    public static Session getDefaultInstance() {
      return defaultInstance;
    }

    public Session getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Session(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionOpcode value = tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionOpcode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                opcode_ = value;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              sessionSecret_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionErrorCode value = tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionErrorCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                errcode_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tud.seemuh.nfcgate.network.c2s.C2S.internal_static_tud_seemuh_nfcgate_network_c2s_Session_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tud.seemuh.nfcgate.network.c2s.C2S.internal_static_tud_seemuh_nfcgate_network_c2s_Session_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tud.seemuh.nfcgate.network.c2s.C2S.Session.class, tud.seemuh.nfcgate.network.c2s.C2S.Session.Builder.class);
    }

    public static com.google.protobuf.Parser<Session> PARSER =
        new com.google.protobuf.AbstractParser<Session>() {
      public Session parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Session(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Session> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code tud.seemuh.nfcgate.network.c2s.Session.SessionOpcode}
     *
     * <pre>
     * Sent by:
     * </pre>
     */
    public enum SessionOpcode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SESSION_CREATE = 0;</code>
       *
       * <pre>
       * Client
       * </pre>
       */
      SESSION_CREATE(0, 0),
      /**
       * <code>SESSION_CREATE_SUCCESS = 1;</code>
       *
       * <pre>
       * Server
       * </pre>
       */
      SESSION_CREATE_SUCCESS(1, 1),
      /**
       * <code>SESSION_CREATE_FAIL = 2;</code>
       *
       * <pre>
       * Server
       * </pre>
       */
      SESSION_CREATE_FAIL(2, 2),
      /**
       * <code>SESSION_JOIN = 3;</code>
       *
       * <pre>
       * Client
       * </pre>
       */
      SESSION_JOIN(3, 3),
      /**
       * <code>SESSION_JOIN_SUCCESS = 4;</code>
       *
       * <pre>
       * Server
       * </pre>
       */
      SESSION_JOIN_SUCCESS(4, 4),
      /**
       * <code>SESSION_JOIN_FAIL = 5;</code>
       *
       * <pre>
       * Server
       * </pre>
       */
      SESSION_JOIN_FAIL(5, 5),
      /**
       * <code>SESSION_LEAVE = 6;</code>
       *
       * <pre>
       * Client
       * </pre>
       */
      SESSION_LEAVE(6, 6),
      /**
       * <code>SESSION_LEAVE_SUCCESS = 7;</code>
       *
       * <pre>
       * Server
       * </pre>
       */
      SESSION_LEAVE_SUCCESS(7, 7),
      /**
       * <code>SESSION_LEAVE_FAIL = 8;</code>
       *
       * <pre>
       * Server
       * </pre>
       */
      SESSION_LEAVE_FAIL(8, 8),
      /**
       * <code>SESSION_PEER_JOINED = 9;</code>
       *
       * <pre>
       * Server
       * </pre>
       */
      SESSION_PEER_JOINED(9, 9),
      /**
       * <code>SESSION_PEER_LEFT = 10;</code>
       *
       * <pre>
       * Server
       * </pre>
       */
      SESSION_PEER_LEFT(10, 10),
      ;

      /**
       * <code>SESSION_CREATE = 0;</code>
       *
       * <pre>
       * Client
       * </pre>
       */
      public static final int SESSION_CREATE_VALUE = 0;
      /**
       * <code>SESSION_CREATE_SUCCESS = 1;</code>
       *
       * <pre>
       * Server
       * </pre>
       */
      public static final int SESSION_CREATE_SUCCESS_VALUE = 1;
      /**
       * <code>SESSION_CREATE_FAIL = 2;</code>
       *
       * <pre>
       * Server
       * </pre>
       */
      public static final int SESSION_CREATE_FAIL_VALUE = 2;
      /**
       * <code>SESSION_JOIN = 3;</code>
       *
       * <pre>
       * Client
       * </pre>
       */
      public static final int SESSION_JOIN_VALUE = 3;
      /**
       * <code>SESSION_JOIN_SUCCESS = 4;</code>
       *
       * <pre>
       * Server
       * </pre>
       */
      public static final int SESSION_JOIN_SUCCESS_VALUE = 4;
      /**
       * <code>SESSION_JOIN_FAIL = 5;</code>
       *
       * <pre>
       * Server
       * </pre>
       */
      public static final int SESSION_JOIN_FAIL_VALUE = 5;
      /**
       * <code>SESSION_LEAVE = 6;</code>
       *
       * <pre>
       * Client
       * </pre>
       */
      public static final int SESSION_LEAVE_VALUE = 6;
      /**
       * <code>SESSION_LEAVE_SUCCESS = 7;</code>
       *
       * <pre>
       * Server
       * </pre>
       */
      public static final int SESSION_LEAVE_SUCCESS_VALUE = 7;
      /**
       * <code>SESSION_LEAVE_FAIL = 8;</code>
       *
       * <pre>
       * Server
       * </pre>
       */
      public static final int SESSION_LEAVE_FAIL_VALUE = 8;
      /**
       * <code>SESSION_PEER_JOINED = 9;</code>
       *
       * <pre>
       * Server
       * </pre>
       */
      public static final int SESSION_PEER_JOINED_VALUE = 9;
      /**
       * <code>SESSION_PEER_LEFT = 10;</code>
       *
       * <pre>
       * Server
       * </pre>
       */
      public static final int SESSION_PEER_LEFT_VALUE = 10;


      public final int getNumber() { return value; }

      public static SessionOpcode valueOf(int value) {
        switch (value) {
          case 0: return SESSION_CREATE;
          case 1: return SESSION_CREATE_SUCCESS;
          case 2: return SESSION_CREATE_FAIL;
          case 3: return SESSION_JOIN;
          case 4: return SESSION_JOIN_SUCCESS;
          case 5: return SESSION_JOIN_FAIL;
          case 6: return SESSION_LEAVE;
          case 7: return SESSION_LEAVE_SUCCESS;
          case 8: return SESSION_LEAVE_FAIL;
          case 9: return SESSION_PEER_JOINED;
          case 10: return SESSION_PEER_LEFT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SessionOpcode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<SessionOpcode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SessionOpcode>() {
              public SessionOpcode findValueByNumber(int number) {
                return SessionOpcode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.c2s.C2S.Session.getDescriptor().getEnumTypes().get(0);
      }

      private static final SessionOpcode[] VALUES = values();

      public static SessionOpcode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private SessionOpcode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tud.seemuh.nfcgate.network.c2s.Session.SessionOpcode)
    }

    /**
     * Protobuf enum {@code tud.seemuh.nfcgate.network.c2s.Session.SessionErrorCode}
     */
    public enum SessionErrorCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ERROR_NOERROR = 0;</code>
       */
      ERROR_NOERROR(0, 0),
      /**
       * <code>ERROR_CREATE_UNKOWN = 1;</code>
       */
      ERROR_CREATE_UNKOWN(1, 1),
      /**
       * <code>ERROR_JOIN_UNKNOWN = 2;</code>
       */
      ERROR_JOIN_UNKNOWN(2, 2),
      /**
       * <code>ERROR_JOIN_UNKNOWN_SECRET = 3;</code>
       */
      ERROR_JOIN_UNKNOWN_SECRET(3, 3),
      /**
       * <code>ERROR_JOIN_SESSION_FULL = 4;</code>
       *
       * <pre>
       * Session already has max # of participants
       * </pre>
       */
      ERROR_JOIN_SESSION_FULL(4, 4),
      /**
       * <code>ERROR_LEAVE_UNKNOWN = 5;</code>
       */
      ERROR_LEAVE_UNKNOWN(5, 5),
      /**
       * <code>ERROR_LEAVE_UNKNOWN_SECRET = 6;</code>
       */
      ERROR_LEAVE_UNKNOWN_SECRET(6, 6),
      /**
       * <code>ERROR_LEAVE_NOT_JOINED = 7;</code>
       *
       * <pre>
       * Trying to leave a session you never joined
       * </pre>
       */
      ERROR_LEAVE_NOT_JOINED(7, 7),
      ;

      /**
       * <code>ERROR_NOERROR = 0;</code>
       */
      public static final int ERROR_NOERROR_VALUE = 0;
      /**
       * <code>ERROR_CREATE_UNKOWN = 1;</code>
       */
      public static final int ERROR_CREATE_UNKOWN_VALUE = 1;
      /**
       * <code>ERROR_JOIN_UNKNOWN = 2;</code>
       */
      public static final int ERROR_JOIN_UNKNOWN_VALUE = 2;
      /**
       * <code>ERROR_JOIN_UNKNOWN_SECRET = 3;</code>
       */
      public static final int ERROR_JOIN_UNKNOWN_SECRET_VALUE = 3;
      /**
       * <code>ERROR_JOIN_SESSION_FULL = 4;</code>
       *
       * <pre>
       * Session already has max # of participants
       * </pre>
       */
      public static final int ERROR_JOIN_SESSION_FULL_VALUE = 4;
      /**
       * <code>ERROR_LEAVE_UNKNOWN = 5;</code>
       */
      public static final int ERROR_LEAVE_UNKNOWN_VALUE = 5;
      /**
       * <code>ERROR_LEAVE_UNKNOWN_SECRET = 6;</code>
       */
      public static final int ERROR_LEAVE_UNKNOWN_SECRET_VALUE = 6;
      /**
       * <code>ERROR_LEAVE_NOT_JOINED = 7;</code>
       *
       * <pre>
       * Trying to leave a session you never joined
       * </pre>
       */
      public static final int ERROR_LEAVE_NOT_JOINED_VALUE = 7;


      public final int getNumber() { return value; }

      public static SessionErrorCode valueOf(int value) {
        switch (value) {
          case 0: return ERROR_NOERROR;
          case 1: return ERROR_CREATE_UNKOWN;
          case 2: return ERROR_JOIN_UNKNOWN;
          case 3: return ERROR_JOIN_UNKNOWN_SECRET;
          case 4: return ERROR_JOIN_SESSION_FULL;
          case 5: return ERROR_LEAVE_UNKNOWN;
          case 6: return ERROR_LEAVE_UNKNOWN_SECRET;
          case 7: return ERROR_LEAVE_NOT_JOINED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SessionErrorCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<SessionErrorCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SessionErrorCode>() {
              public SessionErrorCode findValueByNumber(int number) {
                return SessionErrorCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.c2s.C2S.Session.getDescriptor().getEnumTypes().get(1);
      }

      private static final SessionErrorCode[] VALUES = values();

      public static SessionErrorCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private SessionErrorCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tud.seemuh.nfcgate.network.c2s.Session.SessionErrorCode)
    }

    private int bitField0_;
    public static final int OPCODE_FIELD_NUMBER = 1;
    private tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionOpcode opcode_;
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2s.Session.SessionOpcode opcode = 1;</code>
     *
     * <pre>
     * Opcode
     * describes intent of the message
     * </pre>
     */
    public boolean hasOpcode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2s.Session.SessionOpcode opcode = 1;</code>
     *
     * <pre>
     * Opcode
     * describes intent of the message
     * </pre>
     */
    public tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionOpcode getOpcode() {
      return opcode_;
    }

    public static final int SESSION_SECRET_FIELD_NUMBER = 2;
    private java.lang.Object sessionSecret_;
    /**
     * <code>optional string session_secret = 2;</code>
     *
     * <pre>
     * Session secret
     * Set by server on SESSION_CREATE_SUCCESS
     * Required for SESSION_JOIN, SESSION_LEAVE
     * </pre>
     */
    public boolean hasSessionSecret() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string session_secret = 2;</code>
     *
     * <pre>
     * Session secret
     * Set by server on SESSION_CREATE_SUCCESS
     * Required for SESSION_JOIN, SESSION_LEAVE
     * </pre>
     */
    public java.lang.String getSessionSecret() {
      java.lang.Object ref = sessionSecret_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionSecret_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string session_secret = 2;</code>
     *
     * <pre>
     * Session secret
     * Set by server on SESSION_CREATE_SUCCESS
     * Required for SESSION_JOIN, SESSION_LEAVE
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSessionSecretBytes() {
      java.lang.Object ref = sessionSecret_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionSecret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRCODE_FIELD_NUMBER = 3;
    private tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionErrorCode errcode_;
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2s.Session.SessionErrorCode errcode = 3 [default = ERROR_NOERROR];</code>
     *
     * <pre>
     * Error code
     * Set by server on every message
     * Defaults to ERROR_NOERROR
     * </pre>
     */
    public boolean hasErrcode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2s.Session.SessionErrorCode errcode = 3 [default = ERROR_NOERROR];</code>
     *
     * <pre>
     * Error code
     * Set by server on every message
     * Defaults to ERROR_NOERROR
     * </pre>
     */
    public tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionErrorCode getErrcode() {
      return errcode_;
    }

    private void initFields() {
      opcode_ = tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionOpcode.SESSION_CREATE;
      sessionSecret_ = "";
      errcode_ = tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionErrorCode.ERROR_NOERROR;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOpcode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasErrcode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, opcode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSessionSecretBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, errcode_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, opcode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSessionSecretBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, errcode_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static tud.seemuh.nfcgate.network.c2s.C2S.Session parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Session parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Session parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Session parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Session parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Session parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Session parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Session parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Session parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Session parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tud.seemuh.nfcgate.network.c2s.C2S.Session prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tud.seemuh.nfcgate.network.c2s.Session}
     *
     * <pre>
     * Session management messages
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tud.seemuh.nfcgate.network.c2s.Session)
        tud.seemuh.nfcgate.network.c2s.C2S.SessionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.c2s.C2S.internal_static_tud_seemuh_nfcgate_network_c2s_Session_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tud.seemuh.nfcgate.network.c2s.C2S.internal_static_tud_seemuh_nfcgate_network_c2s_Session_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tud.seemuh.nfcgate.network.c2s.C2S.Session.class, tud.seemuh.nfcgate.network.c2s.C2S.Session.Builder.class);
      }

      // Construct using tud.seemuh.nfcgate.network.c2s.C2S.Session.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        opcode_ = tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionOpcode.SESSION_CREATE;
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionSecret_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        errcode_ = tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionErrorCode.ERROR_NOERROR;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tud.seemuh.nfcgate.network.c2s.C2S.internal_static_tud_seemuh_nfcgate_network_c2s_Session_descriptor;
      }

      public tud.seemuh.nfcgate.network.c2s.C2S.Session getDefaultInstanceForType() {
        return tud.seemuh.nfcgate.network.c2s.C2S.Session.getDefaultInstance();
      }

      public tud.seemuh.nfcgate.network.c2s.C2S.Session build() {
        tud.seemuh.nfcgate.network.c2s.C2S.Session result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tud.seemuh.nfcgate.network.c2s.C2S.Session buildPartial() {
        tud.seemuh.nfcgate.network.c2s.C2S.Session result = new tud.seemuh.nfcgate.network.c2s.C2S.Session(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.opcode_ = opcode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sessionSecret_ = sessionSecret_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errcode_ = errcode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tud.seemuh.nfcgate.network.c2s.C2S.Session) {
          return mergeFrom((tud.seemuh.nfcgate.network.c2s.C2S.Session)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tud.seemuh.nfcgate.network.c2s.C2S.Session other) {
        if (other == tud.seemuh.nfcgate.network.c2s.C2S.Session.getDefaultInstance()) return this;
        if (other.hasOpcode()) {
          setOpcode(other.getOpcode());
        }
        if (other.hasSessionSecret()) {
          bitField0_ |= 0x00000002;
          sessionSecret_ = other.sessionSecret_;
          onChanged();
        }
        if (other.hasErrcode()) {
          setErrcode(other.getErrcode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOpcode()) {
          
          return false;
        }
        if (!hasErrcode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tud.seemuh.nfcgate.network.c2s.C2S.Session parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tud.seemuh.nfcgate.network.c2s.C2S.Session) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionOpcode opcode_ = tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionOpcode.SESSION_CREATE;
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2s.Session.SessionOpcode opcode = 1;</code>
       *
       * <pre>
       * Opcode
       * describes intent of the message
       * </pre>
       */
      public boolean hasOpcode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2s.Session.SessionOpcode opcode = 1;</code>
       *
       * <pre>
       * Opcode
       * describes intent of the message
       * </pre>
       */
      public tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionOpcode getOpcode() {
        return opcode_;
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2s.Session.SessionOpcode opcode = 1;</code>
       *
       * <pre>
       * Opcode
       * describes intent of the message
       * </pre>
       */
      public Builder setOpcode(tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionOpcode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        opcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2s.Session.SessionOpcode opcode = 1;</code>
       *
       * <pre>
       * Opcode
       * describes intent of the message
       * </pre>
       */
      public Builder clearOpcode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        opcode_ = tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionOpcode.SESSION_CREATE;
        onChanged();
        return this;
      }

      private java.lang.Object sessionSecret_ = "";
      /**
       * <code>optional string session_secret = 2;</code>
       *
       * <pre>
       * Session secret
       * Set by server on SESSION_CREATE_SUCCESS
       * Required for SESSION_JOIN, SESSION_LEAVE
       * </pre>
       */
      public boolean hasSessionSecret() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string session_secret = 2;</code>
       *
       * <pre>
       * Session secret
       * Set by server on SESSION_CREATE_SUCCESS
       * Required for SESSION_JOIN, SESSION_LEAVE
       * </pre>
       */
      public java.lang.String getSessionSecret() {
        java.lang.Object ref = sessionSecret_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sessionSecret_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string session_secret = 2;</code>
       *
       * <pre>
       * Session secret
       * Set by server on SESSION_CREATE_SUCCESS
       * Required for SESSION_JOIN, SESSION_LEAVE
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSessionSecretBytes() {
        java.lang.Object ref = sessionSecret_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionSecret_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string session_secret = 2;</code>
       *
       * <pre>
       * Session secret
       * Set by server on SESSION_CREATE_SUCCESS
       * Required for SESSION_JOIN, SESSION_LEAVE
       * </pre>
       */
      public Builder setSessionSecret(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sessionSecret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string session_secret = 2;</code>
       *
       * <pre>
       * Session secret
       * Set by server on SESSION_CREATE_SUCCESS
       * Required for SESSION_JOIN, SESSION_LEAVE
       * </pre>
       */
      public Builder clearSessionSecret() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionSecret_ = getDefaultInstance().getSessionSecret();
        onChanged();
        return this;
      }
      /**
       * <code>optional string session_secret = 2;</code>
       *
       * <pre>
       * Session secret
       * Set by server on SESSION_CREATE_SUCCESS
       * Required for SESSION_JOIN, SESSION_LEAVE
       * </pre>
       */
      public Builder setSessionSecretBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sessionSecret_ = value;
        onChanged();
        return this;
      }

      private tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionErrorCode errcode_ = tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionErrorCode.ERROR_NOERROR;
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2s.Session.SessionErrorCode errcode = 3 [default = ERROR_NOERROR];</code>
       *
       * <pre>
       * Error code
       * Set by server on every message
       * Defaults to ERROR_NOERROR
       * </pre>
       */
      public boolean hasErrcode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2s.Session.SessionErrorCode errcode = 3 [default = ERROR_NOERROR];</code>
       *
       * <pre>
       * Error code
       * Set by server on every message
       * Defaults to ERROR_NOERROR
       * </pre>
       */
      public tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionErrorCode getErrcode() {
        return errcode_;
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2s.Session.SessionErrorCode errcode = 3 [default = ERROR_NOERROR];</code>
       *
       * <pre>
       * Error code
       * Set by server on every message
       * Defaults to ERROR_NOERROR
       * </pre>
       */
      public Builder setErrcode(tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        errcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2s.Session.SessionErrorCode errcode = 3 [default = ERROR_NOERROR];</code>
       *
       * <pre>
       * Error code
       * Set by server on every message
       * Defaults to ERROR_NOERROR
       * </pre>
       */
      public Builder clearErrcode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errcode_ = tud.seemuh.nfcgate.network.c2s.C2S.Session.SessionErrorCode.ERROR_NOERROR;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tud.seemuh.nfcgate.network.c2s.Session)
    }

    static {
      defaultInstance = new Session(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tud.seemuh.nfcgate.network.c2s.Session)
  }

  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tud.seemuh.nfcgate.network.c2s.Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .tud.seemuh.nfcgate.network.c2s.Data.DataErrorCode errcode = 1 [default = ERROR_NOERROR];</code>
     *
     * <pre>
     * Error code
     * Set by the server on every message
     * Defaults to ERROR_NOERROR
     * </pre>
     */
    boolean hasErrcode();
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2s.Data.DataErrorCode errcode = 1 [default = ERROR_NOERROR];</code>
     *
     * <pre>
     * Error code
     * Set by the server on every message
     * Defaults to ERROR_NOERROR
     * </pre>
     */
    tud.seemuh.nfcgate.network.c2s.C2S.Data.DataErrorCode getErrcode();

    /**
     * <code>optional bytes blob = 2;</code>
     *
     * <pre>
     * binary blob
     * Contains the serialized binary blob of the
     * protobuf message that is passed to the other
     * client
     * </pre>
     */
    boolean hasBlob();
    /**
     * <code>optional bytes blob = 2;</code>
     *
     * <pre>
     * binary blob
     * Contains the serialized binary blob of the
     * protobuf message that is passed to the other
     * client
     * </pre>
     */
    com.google.protobuf.ByteString getBlob();
  }
  /**
   * Protobuf type {@code tud.seemuh.nfcgate.network.c2s.Data}
   *
   * <pre>
   * Message passing message
   * Used to pass generic messages between clients
   * </pre>
   */
  public static final class Data extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tud.seemuh.nfcgate.network.c2s.Data)
      DataOrBuilder {
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Data(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Data defaultInstance;
    public static Data getDefaultInstance() {
      return defaultInstance;
    }

    public Data getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              tud.seemuh.nfcgate.network.c2s.C2S.Data.DataErrorCode value = tud.seemuh.nfcgate.network.c2s.C2S.Data.DataErrorCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                errcode_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              blob_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tud.seemuh.nfcgate.network.c2s.C2S.internal_static_tud_seemuh_nfcgate_network_c2s_Data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tud.seemuh.nfcgate.network.c2s.C2S.internal_static_tud_seemuh_nfcgate_network_c2s_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tud.seemuh.nfcgate.network.c2s.C2S.Data.class, tud.seemuh.nfcgate.network.c2s.C2S.Data.Builder.class);
    }

    public static com.google.protobuf.Parser<Data> PARSER =
        new com.google.protobuf.AbstractParser<Data>() {
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Data(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code tud.seemuh.nfcgate.network.c2s.Data.DataErrorCode}
     */
    public enum DataErrorCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ERROR_NOERROR = 0;</code>
       */
      ERROR_NOERROR(0, 0),
      /**
       * <code>ERROR_UNKNOWN = 1;</code>
       */
      ERROR_UNKNOWN(1, 1),
      /**
       * <code>ERROR_NO_SESSION = 2;</code>
       */
      ERROR_NO_SESSION(2, 2),
      /**
       * <code>ERROR_TRANSMISSION_FAILED = 3;</code>
       */
      ERROR_TRANSMISSION_FAILED(3, 3),
      ;

      /**
       * <code>ERROR_NOERROR = 0;</code>
       */
      public static final int ERROR_NOERROR_VALUE = 0;
      /**
       * <code>ERROR_UNKNOWN = 1;</code>
       */
      public static final int ERROR_UNKNOWN_VALUE = 1;
      /**
       * <code>ERROR_NO_SESSION = 2;</code>
       */
      public static final int ERROR_NO_SESSION_VALUE = 2;
      /**
       * <code>ERROR_TRANSMISSION_FAILED = 3;</code>
       */
      public static final int ERROR_TRANSMISSION_FAILED_VALUE = 3;


      public final int getNumber() { return value; }

      public static DataErrorCode valueOf(int value) {
        switch (value) {
          case 0: return ERROR_NOERROR;
          case 1: return ERROR_UNKNOWN;
          case 2: return ERROR_NO_SESSION;
          case 3: return ERROR_TRANSMISSION_FAILED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataErrorCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<DataErrorCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataErrorCode>() {
              public DataErrorCode findValueByNumber(int number) {
                return DataErrorCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.c2s.C2S.Data.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataErrorCode[] VALUES = values();

      public static DataErrorCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private DataErrorCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tud.seemuh.nfcgate.network.c2s.Data.DataErrorCode)
    }

    private int bitField0_;
    public static final int ERRCODE_FIELD_NUMBER = 1;
    private tud.seemuh.nfcgate.network.c2s.C2S.Data.DataErrorCode errcode_;
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2s.Data.DataErrorCode errcode = 1 [default = ERROR_NOERROR];</code>
     *
     * <pre>
     * Error code
     * Set by the server on every message
     * Defaults to ERROR_NOERROR
     * </pre>
     */
    public boolean hasErrcode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .tud.seemuh.nfcgate.network.c2s.Data.DataErrorCode errcode = 1 [default = ERROR_NOERROR];</code>
     *
     * <pre>
     * Error code
     * Set by the server on every message
     * Defaults to ERROR_NOERROR
     * </pre>
     */
    public tud.seemuh.nfcgate.network.c2s.C2S.Data.DataErrorCode getErrcode() {
      return errcode_;
    }

    public static final int BLOB_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString blob_;
    /**
     * <code>optional bytes blob = 2;</code>
     *
     * <pre>
     * binary blob
     * Contains the serialized binary blob of the
     * protobuf message that is passed to the other
     * client
     * </pre>
     */
    public boolean hasBlob() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes blob = 2;</code>
     *
     * <pre>
     * binary blob
     * Contains the serialized binary blob of the
     * protobuf message that is passed to the other
     * client
     * </pre>
     */
    public com.google.protobuf.ByteString getBlob() {
      return blob_;
    }

    private void initFields() {
      errcode_ = tud.seemuh.nfcgate.network.c2s.C2S.Data.DataErrorCode.ERROR_NOERROR;
      blob_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasErrcode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, errcode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, blob_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, errcode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, blob_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static tud.seemuh.nfcgate.network.c2s.C2S.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tud.seemuh.nfcgate.network.c2s.C2S.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tud.seemuh.nfcgate.network.c2s.C2S.Data prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tud.seemuh.nfcgate.network.c2s.Data}
     *
     * <pre>
     * Message passing message
     * Used to pass generic messages between clients
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tud.seemuh.nfcgate.network.c2s.Data)
        tud.seemuh.nfcgate.network.c2s.C2S.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tud.seemuh.nfcgate.network.c2s.C2S.internal_static_tud_seemuh_nfcgate_network_c2s_Data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tud.seemuh.nfcgate.network.c2s.C2S.internal_static_tud_seemuh_nfcgate_network_c2s_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tud.seemuh.nfcgate.network.c2s.C2S.Data.class, tud.seemuh.nfcgate.network.c2s.C2S.Data.Builder.class);
      }

      // Construct using tud.seemuh.nfcgate.network.c2s.C2S.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        errcode_ = tud.seemuh.nfcgate.network.c2s.C2S.Data.DataErrorCode.ERROR_NOERROR;
        bitField0_ = (bitField0_ & ~0x00000001);
        blob_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tud.seemuh.nfcgate.network.c2s.C2S.internal_static_tud_seemuh_nfcgate_network_c2s_Data_descriptor;
      }

      public tud.seemuh.nfcgate.network.c2s.C2S.Data getDefaultInstanceForType() {
        return tud.seemuh.nfcgate.network.c2s.C2S.Data.getDefaultInstance();
      }

      public tud.seemuh.nfcgate.network.c2s.C2S.Data build() {
        tud.seemuh.nfcgate.network.c2s.C2S.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tud.seemuh.nfcgate.network.c2s.C2S.Data buildPartial() {
        tud.seemuh.nfcgate.network.c2s.C2S.Data result = new tud.seemuh.nfcgate.network.c2s.C2S.Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errcode_ = errcode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.blob_ = blob_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tud.seemuh.nfcgate.network.c2s.C2S.Data) {
          return mergeFrom((tud.seemuh.nfcgate.network.c2s.C2S.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tud.seemuh.nfcgate.network.c2s.C2S.Data other) {
        if (other == tud.seemuh.nfcgate.network.c2s.C2S.Data.getDefaultInstance()) return this;
        if (other.hasErrcode()) {
          setErrcode(other.getErrcode());
        }
        if (other.hasBlob()) {
          setBlob(other.getBlob());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasErrcode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tud.seemuh.nfcgate.network.c2s.C2S.Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tud.seemuh.nfcgate.network.c2s.C2S.Data) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private tud.seemuh.nfcgate.network.c2s.C2S.Data.DataErrorCode errcode_ = tud.seemuh.nfcgate.network.c2s.C2S.Data.DataErrorCode.ERROR_NOERROR;
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2s.Data.DataErrorCode errcode = 1 [default = ERROR_NOERROR];</code>
       *
       * <pre>
       * Error code
       * Set by the server on every message
       * Defaults to ERROR_NOERROR
       * </pre>
       */
      public boolean hasErrcode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2s.Data.DataErrorCode errcode = 1 [default = ERROR_NOERROR];</code>
       *
       * <pre>
       * Error code
       * Set by the server on every message
       * Defaults to ERROR_NOERROR
       * </pre>
       */
      public tud.seemuh.nfcgate.network.c2s.C2S.Data.DataErrorCode getErrcode() {
        return errcode_;
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2s.Data.DataErrorCode errcode = 1 [default = ERROR_NOERROR];</code>
       *
       * <pre>
       * Error code
       * Set by the server on every message
       * Defaults to ERROR_NOERROR
       * </pre>
       */
      public Builder setErrcode(tud.seemuh.nfcgate.network.c2s.C2S.Data.DataErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        errcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .tud.seemuh.nfcgate.network.c2s.Data.DataErrorCode errcode = 1 [default = ERROR_NOERROR];</code>
       *
       * <pre>
       * Error code
       * Set by the server on every message
       * Defaults to ERROR_NOERROR
       * </pre>
       */
      public Builder clearErrcode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errcode_ = tud.seemuh.nfcgate.network.c2s.C2S.Data.DataErrorCode.ERROR_NOERROR;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString blob_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes blob = 2;</code>
       *
       * <pre>
       * binary blob
       * Contains the serialized binary blob of the
       * protobuf message that is passed to the other
       * client
       * </pre>
       */
      public boolean hasBlob() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes blob = 2;</code>
       *
       * <pre>
       * binary blob
       * Contains the serialized binary blob of the
       * protobuf message that is passed to the other
       * client
       * </pre>
       */
      public com.google.protobuf.ByteString getBlob() {
        return blob_;
      }
      /**
       * <code>optional bytes blob = 2;</code>
       *
       * <pre>
       * binary blob
       * Contains the serialized binary blob of the
       * protobuf message that is passed to the other
       * client
       * </pre>
       */
      public Builder setBlob(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        blob_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes blob = 2;</code>
       *
       * <pre>
       * binary blob
       * Contains the serialized binary blob of the
       * protobuf message that is passed to the other
       * client
       * </pre>
       */
      public Builder clearBlob() {
        bitField0_ = (bitField0_ & ~0x00000002);
        blob_ = getDefaultInstance().getBlob();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tud.seemuh.nfcgate.network.c2s.Data)
    }

    static {
      defaultInstance = new Data(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tud.seemuh.nfcgate.network.c2s.Data)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tud_seemuh_nfcgate_network_c2s_Session_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tud_seemuh_nfcgate_network_c2s_Session_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tud_seemuh_nfcgate_network_c2s_Data_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tud_seemuh_nfcgate_network_c2s_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tc2s.proto\022\036tud.seemuh.nfcgate.network." +
      "c2s\"\300\005\n\007Session\022E\n\006opcode\030\001 \002(\01625.tud.se" +
      "emuh.nfcgate.network.c2s.Session.Session" +
      "Opcode\022\026\n\016session_secret\030\002 \001(\t\022X\n\007errcod" +
      "e\030\003 \002(\01628.tud.seemuh.nfcgate.network.c2s" +
      ".Session.SessionErrorCode:\rERROR_NOERROR" +
      "\"\221\002\n\rSessionOpcode\022\022\n\016SESSION_CREATE\020\000\022\032" +
      "\n\026SESSION_CREATE_SUCCESS\020\001\022\027\n\023SESSION_CR" +
      "EATE_FAIL\020\002\022\020\n\014SESSION_JOIN\020\003\022\030\n\024SESSION" +
      "_JOIN_SUCCESS\020\004\022\025\n\021SESSION_JOIN_FAIL\020\005\022\021",
      "\n\rSESSION_LEAVE\020\006\022\031\n\025SESSION_LEAVE_SUCCE" +
      "SS\020\007\022\026\n\022SESSION_LEAVE_FAIL\020\010\022\027\n\023SESSION_" +
      "PEER_JOINED\020\t\022\025\n\021SESSION_PEER_LEFT\020\n\"\347\001\n" +
      "\020SessionErrorCode\022\021\n\rERROR_NOERROR\020\000\022\027\n\023" +
      "ERROR_CREATE_UNKOWN\020\001\022\026\n\022ERROR_JOIN_UNKN" +
      "OWN\020\002\022\035\n\031ERROR_JOIN_UNKNOWN_SECRET\020\003\022\033\n\027" +
      "ERROR_JOIN_SESSION_FULL\020\004\022\027\n\023ERROR_LEAVE" +
      "_UNKNOWN\020\005\022\036\n\032ERROR_LEAVE_UNKNOWN_SECRET" +
      "\020\006\022\032\n\026ERROR_LEAVE_NOT_JOINED\020\007\"\324\001\n\004Data\022" +
      "R\n\007errcode\030\001 \002(\01622.tud.seemuh.nfcgate.ne",
      "twork.c2s.Data.DataErrorCode:\rERROR_NOER" +
      "ROR\022\014\n\004blob\030\002 \001(\014\"j\n\rDataErrorCode\022\021\n\rER" +
      "ROR_NOERROR\020\000\022\021\n\rERROR_UNKNOWN\020\001\022\024\n\020ERRO" +
      "R_NO_SESSION\020\002\022\035\n\031ERROR_TRANSMISSION_FAI" +
      "LED\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tud_seemuh_nfcgate_network_c2s_Session_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tud_seemuh_nfcgate_network_c2s_Session_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tud_seemuh_nfcgate_network_c2s_Session_descriptor,
        new java.lang.String[] { "Opcode", "SessionSecret", "Errcode", });
    internal_static_tud_seemuh_nfcgate_network_c2s_Data_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tud_seemuh_nfcgate_network_c2s_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tud_seemuh_nfcgate_network_c2s_Data_descriptor,
        new java.lang.String[] { "Errcode", "Blob", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
