plugins {
    id 'com.android.library'
}

android {
    compileSdk = 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 36
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    productFlavors {}

    namespace 'de.tu_darmstadt.seemoo.nfcgate.common'

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation project(':protobuf')
    implementation "com.google.protobuf:protobuf-javalite:${protobufVersion}"
}